### ISSUE TITLE
Support for Mobile Data tethering

### ISSUE THREAD

**Issue by RenanEuzebio** [pyamsoft/tetherfi#104]
I would first like to say I really like your app!

It works very well and I appreciate all the work that has been put into it. I managed to tether my Wi-Fi connection without any problems, but I always fail to do the same with my data. Is it possible to implement that feature as an alternative for the default hotspot/USB tethering?

Cheers!

**Comment by pyamsoft** [comment]
Hi there, thanks for the kind words.

I think there's a misunderstanding, the app already works as a mobile data hotspot. That is, in fact, how I use it myself.

The app works as a proxy. In non technical terms, your computer tells your phone to load a webpage. Your phone talks to the internet over whatever connection it has, and then relays that information back to your computer like a middleman.

This should work regardless of how your phone is connected to the Internet. One caveat though is that WiFi must be enabled on your phone, even though it doesn't need to actually be connected to anything. WiFi must be on so the phone can create the Tetherfi WiFi network that your computer connects to.

When you use the app over mobile data, where do you get stuck? Is there an error launching the tetherfi hotspot? Or does it run the hotspot fine but your computer can't actually connect to it?
