### ISSUE TITLE
Suggestion to Hide Hotspot Details and Add QR Code Support

### ISSUE THREAD

**Issue by zellchristensen** [pyamsoft/tetherfi#110]
Would be nice if to have an option to that displayed the hotspot password and/or name and other settings  behind starts (*******) with an option to show/hide the details.  That way you don't just have the password on screen when the app is open.

Would also be neat to have an option to display a QR code for the access point to avoid having to manually type out a long complex password on another device.

**Comment by pyamsoft** [comment]
Hi

These are both good ideas. I will create a visibility toggle for password only though, as the SSID is not a secure piece of information (since we don't have a way of hiding SSID on Android)

I will also look into QR creation

**Comment by pyamsoft** [comment]
These features have been added on to main. Once I cut a release on the store that includes these, I will complete this issue. Thanks!
