### ISSUE TITLE
Suggestion: Option to Disable Prepending of "DIRECT-TF-" String to Hotspot Name/SSID

### ISSUE THREAD

**Issue by zellchristensen** [pyamsoft/tetherfi#111]
The string "DIRECT-TF-" is always prepended to the desired Hotspot Name/SSID making it obvious that TetherFi is being used.  While not that big a deal, it's not really obvious that it's going to even happen until after starting the hotspot

**Comment by pyamsoft** [comment]
Hi, the DIRECT prefix is an Android requirement.

I will update the UI to make this prefix more obvious though during editing

**Comment by pyamsoft** [comment]
Hi, the DIRECT prefix is an Android requirement.

I will update the UI to make this prefix more obvious though during editing

**Comment by pyamsoft** [comment]
This feature has been added on to main. Once I cut a release on the store that includes this, I will complete this issue. Thanks!
