### ISSUE TITLE
Add an option to only use WiFi for upstream

### ISSUE THREAD

**Issue by proski** [pyamsoft/tetherfi#115]
The whole reason for WiFi sharing apps is to share a free WiFi connection (I can use the standard hotspot functionality to share mobile internet). I want to have an option (preferably on by default) to ensure that the app won't use mobile internet if the upstream WiFi connection breaks. I don't want to pay a higher bill if the disconnect happens while downloading a big file.

**Comment by pyamsoft** [comment]
Hi, since this is a simple proxy application, it is out of scope for it to decide to act based on connection state, sorry.

I recommend looking at other solutions for strict WiFi sharing.

**Comment by proski** [comment]
There are not so many solutions for WiFi sharing without root. The solution I've been using so far is "NetShare no-root-tethering". I believe there another closed source app, PdaNet+. This is the third solution, finally an open source app. Neither has an option to limit traffic to WiFi.

My use cases for sharing mobile data and WiFi are different.

Sharing mobile data: I'm driving and sharing my internet connection with other passengers who don't have mobile data. The passengers are told not use download big files. The hotspot functionality is perfect for that, there is no proxy.

Sharing WiFi: I'm working on my laptop in a park with a weak WiFi signal that only my phone can receive more or less reliably if oriented a certain way. I start a large download. The WiFi signal gets too weak even for the phone. The phone switches to mobile data, my phone bill gets more expensive.

Sure, I can disable mobile data. The problem is that the use of mobile data happens accidentally and I don't want to have another setting to change and another thing to worry about.

**Comment by pyamsoft** [comment]
Yes sadly with modern Android developments there are very few realistic ways to reliably determine whether traffic from a device is from a WiFi or Mobile Data radio.

At the socket level that tetherfi operates on, there is no way that I know of to determine which traffic source is being used.

Let me be clear, the solution certainly may exist, but is outside of my ability to discover and implement. I welcome any contributions for this feature but will not be able to add this feature as things currently stand.

**Comment by proski** [comment]
OK, good to know. Thank you for the explanation!
