### ISSUE TITLE
Better explanation

### ISSUE THREAD

**Issue by pyamsoft** [pyamsoft/tetherfi#116]
On readme and store

Share WiFi or Mobile Data
Avoid hotspot data caps
Avoid hotspot data throttling
Run a hotspot without a hotspot plan
Create a local network between devices
Potentially share your VPN connection if VPN app allows (TailScale and Mullvad possibly confirmed)

**Comment by MinekPo1** [comment]
Additional use case: bypass device limit on network

**Comment by pyamsoft** [comment]
Readme

486d81ad94b54b22b2aebb180457746a523cd23e
