### ISSUE TITLE
asks for pin

### ISSUE THREAD

**Issue by garfieldbanks** [pyamsoft/tetherfi#125]
When attempting to connect to the hotspot from a windows device it asks for a pin. I tried the password I set in the android app but it didn't work. What have I done wrong?

**Comment by pyamsoft** [comment]
Sorry, I have no idea about the specifics of Windows connections.

I would treat this in two parts

1. Connect to the WiFi network. You should be able to do this just like any other WiFi network by entering the name and password.

2. Make sure the network gets connected to the Internet.
Once you are connected to the hotspot WiFi, now try inputting the proxy settings into Windows.

Any screenshots you can take of your Android or Windows would help

**Comment by garfieldbanks** [comment]
Am I supposed to be able to connect to wifi on the android device itself first? Because I'm trying that (tried both manually entering all the details and also using the QR code) and it doesn't ever seem to see the the hotspot I created (in tetherFi). In the tetherFi app the broadcast, proxy, and hotspot statuses are all running.

At this point I try to connect to the wifi from windows and I get this prompt:
![image](https://user-images.githubusercontent.com/12904270/216181032-5e8196a1-69f4-46ab-8484-42051c56243d.png)

**Comment by garfieldbanks** [comment]
Am I supposed to be able to see the wifi from within the same device that creates it using tetherFi?

**Comment by pyamsoft** [comment]
You should have two devices

1, and Andoid running TetherFi that is already connected to the Internet.

Two your Windows PC which does not have internet.

After starting Tetherfi on your Android, you should be able to see it on Windows in the WiFi network menu.

Select the Tetherfi network and click Connect using a security key instead. Enter the password you set up in Tetherfi. Once you are connected on Windows, you won't have Internet yet. Set the proxy settings on Windows and then Tetherfi will be able to share your Android internet with windows.

**Comment by pyamsoft** [comment]
Your Android phone will not be able to see the Tetherfi network, as it is the one broadcasting it.

**Comment by garfieldbanks** [comment]
OK I got it working on both windows 11 and windows 10. I had to find the manual proxy settings. On 11 I was able to use the UI to connect but on windows 10 I had to manually create the wifi entry.
Windows 11:
![image](https://user-images.githubusercontent.com/12904270/216184942-039ef3f8-7fc6-467c-835d-7c61dde2458d.png)

Windows 10:
![image](https://user-images.githubusercontent.com/12904270/216187167-0af6bbe6-72ec-4e6e-b06b-7d83427f7405.png)
and
![image](https://user-images.githubusercontent.com/12904270/216187596-5f74c933-e992-44f4-a6c6-5533426d4f31.png)

Now the problem is getting it to use a VPN. Any reason why a VPN wouldn't be able to connect through this? I can't seem to get it to connect...

**Comment by pyamsoft** [comment]
Glad to hear

Sadly VPNs are generally not supported. Only a select few have been shown to work, and they must be running on the Android device and allowing LAN connections.

I do not think its possible at the moment to connect to a VPN from your Windows device unless the VPN app provides specific proxy settings.

Most VPNs use OpenVPN UDP or Wireguard, which Tetherfi cannot proxy yet.

**Comment by garfieldbanks** [comment]
Mine has TCP options. Should that work somehow?

**Comment by pyamsoft** [comment]
It may but that depends on the VPN. At the point you're at you are proxied to Tetherfi, and anything else is sadly out of my hands.

If you do manage to get your VPN working, I'd love if you could comment which VPN you were using and what kind of settings you used

**Comment by garfieldbanks** [comment]
I did get the vpn working as you said on the android device only using the "stealth" option. Not sure what that does but it works, at least I can get a browser window to report a changed ip from iplocation.net. But I don't know how to get p2p working. Which interface do I bind to on in my torrent client?

**Comment by pyamsoft** [comment]
I'm not sure. It sounds like the proxy part of tetherfi is working so this sounds out of scope for this application.

I'd reach out to your Torrent developer and see what they say about it.
