### ISSUE TITLE
No Proxy IP [Bug]/[New Features]

### ISSUE THREAD

**Issue by Reggie2561** [pyamsoft/tetherfi#131]
Hey, i been using this app for about 2 to 3 weeks now. At first it was working perfecting and I was able to tether my WiFi through my phone. But recently it started to pop up saying: "NO IP ADDRESS" in the section where the proxy's IP should be. 
![Screenshot_20230206-160205](https://user-images.githubusercontent.com/89669127/217088929-59ff0d3f-a659-4737-8f65-b4433089ce9e.png)

Also I would love to see the devices I have connected to the hotspot that is created and I feel like it would be extremely helpful if there was a way to block certain internal and external IP address or URLs from being able to connect.

**Comment by pyamsoft** [comment]
Hi,

Showing connected devices has an issue and is in progress.

Odd that it can't find an IP address. Usually I think it defaults to 192.168.49.1

Once the hotspot is running the app fires off a call asking what the IP address is - so if that is not coming back something is non standard with your device.

Does the network still work if you assume the Proxy URL is at 192.168.49.1?

**Comment by pyamsoft** [comment]
If you switch to 2.4 GHz band, does the IP address come back?

**Comment by Reggie2561** [comment]
I change the Band to 2.4 GHZ it still does not work, it shows the same thing. I tried to connecting to the HTTPS proxy but it seems like it doesn't want to connect. I also tried: restarting my devices. clearing cache and data, uninstalling and reinstalling the app. But still the same issue reappears. Is there any google related components it uses? Since I been de-googling my phone recently it might of caused the bug.

**Comment by pyamsoft** [comment]
There are no google dependencies at least relating to the hotspot broadcast.

The hotspot relies purely on WiFi Direct on your phone.

Did it ever work? The code for populating the IP address has not changed since the initial release, so I wonder what's going on

**Comment by Reggie2561** [comment]
Yes, it worked for able two weeks and then it started to show this bug yesterday.

**Comment by Reggie2561** [comment]
If you want I can run ADB logging to get you more specific details.

**Comment by pyamsoft** [comment]
Odd, OK

Again, the network code hasn't changed for a bit so I'm unsure if this is caused by your device (though I doubt it)

I will look to trying to make the IP resolution more reliable.


Just to be sure, you are able to

1. Run the hotspot
2. See the WiFi network and connect to it from another device.

But you are unable once connected to setup a proxy because you are missing the Proxy URL, right?

**Comment by Reggie2561** [comment]
I ran a check if there is a Gateway IP Address that the hotspot puts out. But it doesn't seem to have one, its broadcasting the Band but not giving out a Gateway IP Address.

**Comment by pyamsoft** [comment]
Hello

When you have the chance, I've uploaded release version 20 to Github and the Play Store. This release adds some additional in-app debugging which may show for you if something goes wrong when retrieving the hotspot info from WiFi Direct on the device.

Please update when you can, and see if anything changes about your situtation, thanks.

**Comment by pyamsoft** [comment]
Ah ive  also just noticed from your screenshot, you have a VPN running on your Android device.

If you turn off the VPN first and then attempt to connect to TetherFi does your IP address get populated?

**Comment by Reggie2561** [comment]
Sorry for late reply i been busy
![Screenshot_20230207-081633](https://user-images.githubusercontent.com/89669127/217256487-2050bc3a-538f-4ddb-b1c8-e5c83b127aa6.png)

**Comment by pyamsoft** [comment]
Hmm interesting, this could be one of two issues.

One, race condition, the app is asking for Connection info too early, and we just need to wait a little longer

Or two, WiFi direct is failing to fully setup, and so there just is no available connection info ever.

I will implement some code that asks for connection info slower, hoping that this is just case 1.

Thanks for testing the new in-app error dialog feature too! :stuck_out_tongue:

**Comment by pyamsoft** [comment]
Recent updates have added a "Refresh Hotspot" button which should attempt to ask the underlying Wifi system to get the IP address again. Please see if this refresh action solves your problem of missing an IP address, thank you!
