### ISSUE TITLE
Generated password displayed in ambiguous font (lowercase L and uppercase i are identical)

### ISSUE THREAD

**Issue by Dwedit** [pyamsoft/tetherfi#140]
I was just trying out tetherfi, and it seems to work well, except I had to do a second attempt at entering the Wifi password, as it turned out that the first letter was actually a lowercase L and not an uppercase i.

Perhaps switch to the system's fixed width font to display that instead of the default font.

**Comment by pyamsoft** [comment]
Hi

TetherFi does use the system default Monospace font for displaying content.

I will look at trying to avoid ambiguous characters in auto generated

**Comment by Dwedit** [comment]
Thank you for the quick response!

On my phone, the font looks like this:  (not a monospaced font)

![screenshot](https://i.imgur.com/O8IHLGP.png)

**Comment by pyamsoft** [comment]
Hi, update to the latest version of TetherFi, your screenshot shows an out of date version

**Comment by Dwedit** [comment]
Thanks again.  My copy of the program apparently came from the "IzzyOnDroid F-Droid Repository" (https://apt.izzysoft.de/fdroid/), and was outdated, I've redownloaded it from the play store instead.
