### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [pyamsoft/tetherfi#152]
Please support the Android 13 "Themed App Icons" feature.

![Screenshot_2023-03-24-07-38-45-338_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/227422121-fb55c148-8405-4139-81a3-2e4a4d1dcdb8.jpg)

Thanks 🙏

**Comment by pyamsoft** [comment]
The next release will have support for monochrome

It will release whenever I can get a screen in the app to show connected hotspot devices.

Thanks!

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by pyamsoft** [comment]
Version 22 is in testing and should release on the store in the next couple of days, this should bring suport for monochrome icons.

I do not have a monochrome icon supported launcher, so please test when the new version comes to your device and see if this is resolved. Thank you!

**Comment by xmha97** [comment]
Thanks, please release this version on the GitHub.
I don't have access to Play Store.
Thanks.

**Comment by pyamsoft** [comment]
The latest release is out on github

**Comment by xmha97** [comment]
Thanks but why the background is not simple?
The purpose of this feature is the uniformity of the icons, in this case the purpose will not be achieved.

![Screenshot_2023-03-26-01-38-05-562_de mm20 launcher2 release](https://user-images.githubusercontent.com/23485114/227744656-da5c417d-0990-40df-aa10-643039c2d925.jpg)

**Comment by pyamsoft** [comment]
Again, since I don't actually have a launcher that supports monochrome I was unable to actually test.
Thus, I didn't know what it looked like at all. I will see about removing the background mask from the iconography

**Comment by xmha97** [comment]
Ok, you can use this launcher:
https://github.com/MM2-0/Kvaesitso

![Screenshot_2023-03-26-04-32-29-525_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/227749626-66bc6d6a-a653-40c0-ab8e-8169e39cd5ff.jpg)

![Screenshot_2023-03-26-04-32-35-386_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/227749627-1c5df6fc-c03f-4681-9537-89cdc24c7e73.jpg)
