### ISSUE TITLE
Wifiman shows insane upload speeds

### ISSUE THREAD

**Issue by nate-moo** [pyamsoft/tetherfi#180]
![1685323787906.jpg](https://github.com/pyamsoft/tetherfi/assets/40650681/57568762-d759-44a3-af44-bbcc9269b7dc)

latest build from fdroid

**Comment by pyamsoft** [comment]
What's the problem here?

**Comment by nate-moo** [comment]
I only get about 10mbps on the phone but over this app it shows 100+

**Comment by pyamsoft** [comment]
No idea, I dont control how wifiman measures upload speed. Its out of scope for this app.
