### ISSUE TITLE
Great but really laggy

### ISSUE THREAD

**Issue by Gone-Dark** [pyamsoft/tetherfi#182]
This app is great! I love it as a free and open-source version of pdanet. However my only complaint is that whenever I start the hotspot, my phone because extremely laggy, at one point crashing. The app makes my phone very slow and laggy, making it hard to do anything on it.

**Comment by pyamsoft** [comment]
Yes ive noticed this too. Recent dev versions should have caught some bad memory leaks that were causing extreme slowdown. The next version should perform hopefully much better, I plan to release the new version in a week or so, please stay patient!

**Comment by pyamsoft** [comment]
A new version has been pushed to the play store open testing track, and is available on github as release 24. Please check this release as major fixes have been made to the hotspot code to make it faster and it should no longer lag the system. Please see if your device slowdown issues are fixed or at least made easier to manage.

As a post-mortem: A bug was found in the hotspot proxy code which would cause a programming loop to run forever, never stopped and never freeing resources up for other device tasks. As a result, each new connection would create a new never-ending loop, causing the device to get slower and slower with each interaction, eventually causing it to get so slow the system would halt.

**Comment by pyamsoft** [comment]
Version 24 is out on the Play store and should help resolve these performance issues. I will leave this issue open for another week for followup comments, but hopefully the performance impact has been resolved.

**Comment by Gone-Dark** [comment]
Seems to be working well and not laggy! Thank you for fixing it.

**Comment by pyamsoft** [comment]
Great! I'll close this one for now. Thanks for reporting!
