### ISSUE TITLE
[Request] Ability to change / disable prefix

### ISSUE THREAD

**Issue by joe733** [pyamsoft/tetherfi#183]
Currently `DIRECT-TF-` can't be changed.

![Imagepipe_0.jpg](https://github.com/pyamsoft/tetherfi/assets/38415384/f9a6171b-7697-4f6b-9c20-509668de124e)

I would like to have an option to change or disable it entirely.

**Comment by pyamsoft** [comment]
Sorry, no can do. The `DIRECT-` prefix is a hard requirement for WiFi direct networks on Android. Sorry.
