### ISSUE TITLE
Phone is unresponsive and warm when running TetherFi

### ISSUE THREAD

**Issue by Dwedit** [pyamsoft/tetherfi#184]
I don't know the best way to diagnose this problem, but I'm seeing my phone (Moto G7 Power) become very unresponsive (and warm to the touch) while running the wifi services using TetherFi.  Even just unlocking the phone takes a long time.

**Comment by pyamsoft** [comment]
Hi, this was a bug in an older version of TetherFi

A new version was released yesterday, version 24. Please update.

**Comment by pyamsoft** [comment]
Please let me know if updating to version 24 fixes your performance issues. Thank you!

**Comment by pyamsoft** [comment]
Will close if no response in 2 days, please use version 24, thank you!

**Comment by Dwedit** [comment]
I was indeed running an old version, and I have not seen it happen since upgrading, but I haven't really used it that much.  That said, I wasn't closing the bug out of consideration of people filing duplicates.
