### ISSUE TITLE
Suggestion: Documentation for how to set up a proxy configuration script on Windows

### ISSUE THREAD

**Issue by Dwedit** [pyamsoft/tetherfi#185]
Basically you need this:

* Install and run an HTTP server running on your local computer (bound to localhost only), I put mine on port 54321
* This Javascript File, saved as "C:\httpserver\proxy.pac"
```
function FindProxyForURL (url, host)
{
	if (isInNet(myIpAddress(), "192.168.49.0", "255.255.255.0")) return 'PROXY 192.168.49.1:8228; DIRECT';
	return 'DIRECT';
}
```
* The script matches TetherFi's default settings.
  * If you changed anything, make the changes in that script as well.
  * Match the IP address range, Proxy's IP and Proxy's port number.
  * If you normally need to use a proxy server, replace `return 'DIRECT';` with `return 'PROXY ip-address:port-number; DIRECT';`
* Set system proxy settings to use http:\//127.0.0.1:54321/proxy.pac
  * WindowsKey+R, run "inetcpl.cpl"  (This is Internet Options on the Control Panel)
  * "Connections" Tab, "LAN settings" button
  * Turn off "Automatically detect settings", turn on "Use automatic configuration script", set address to `http://127.0.0.1:54321/proxy.pac`
* Set web browser proxy settings to use system proxy settings

---

Setting up the web server and making it auto-start is the hardest part.  What I personally did:

* Install Python 3 with "http.server" module
* Create a scheduled task to run the server at logon time without showing any window
  * Pretty complicated actually, in order to hide the command prompt window, I had to use "nircmd.exe" from NirSoft.
  * My command ended up being program `C:\path-to-nircmd\nircmd.exe` with arguments `exec hide cmd.exe /C C:\Python38\Python.exe -m http.server --bind 127.0.0.1 --directory C:\httpserver 54321`
  * Triggers: "At log on"
  * Disable "Start the task only if running on AC power"
  * Disable "Stop the task if it runs longer than" some time
  * Ensure it's set to "Do not start new instance" if already running
* After creating the task, Right click and Run, then try loading http://127.0.0.1:54321 in your web browser.

**Comment by pyamsoft** [comment]
Thank you for the documentation. I will close this issue, to keep the queue clean, but I will pin this issue so that future readers can find it easily. Thanks!
