### ISSUE TITLE
Connected to internet but not working properly 

### ISSUE THREAD

**Issue by Countryangel80** [pyamsoft/tetherfi#191]
I have devices connected to Tether-fi and it works to an extent but certain things do not work properly. I am not able to use my Facebook Messenger, I can access it but then it just says connecting and never connects therefore I cannot use it. Cash App also doesn't update or show any new transactions since the last time my device was connected to the internet with complete access.

**Comment by pyamsoft** [comment]
Being connected to the Wi-Fi direct network, and having internet access are two different steps in TetherFi. Did you configure the proxy settings on your connecting devices as stated in the instructions?

**Comment by Countryangel80** [comment]
Yes, I entered the correct proxy settings and it is connected which is why I have internet but all things aren't working properly like the two I listed above

**Comment by pyamsoft** [comment]
Please include screenshots of the status page when TetherFi is running.

What device are you connecting to TetherFi, another phone or a laptop?

**Comment by Countryangel80** [comment]
![Screenshot_20230709-134553](https://github.com/pyamsoft/tetherfi/assets/139072276/09d8943b-1751-44bb-ac91-5df0b4efb2b1)
 I am using another phone to connect to TetherFi

**Comment by pyamsoft** [comment]
Other apps work fine on the TetherFi connection, and it's just Messenger and Cash App?

**Comment by Countryangel80** [comment]
Yes, as I can tell at the moment those are the only two not working properly

**Comment by Countryangel80** [comment]
I just checked and I also can't access a game I downloaded an apk for

**Comment by pyamsoft** [comment]
Support for online gaming is still a work in progress, so it's unfortunately expected at the moment that games won't work. Messenger though should work fine, so I am trying to figure out why it's not

**Comment by Countryangel80** [comment]
Ok thank you, please let me know anything you come up with that I can try and maybe we can get it working

**Comment by pyamsoft** [comment]
It seems like something has indeed broken with Facebook Messengers android app, it doesn't like proxy connections anymore.

Weirdly enough, you can SEND messages, you just can't RECEIVE any (it is a little slow, I'll work to speed up the performance)

What does seem to work though is using Messenger on a proxy through a mobile web browser (which always honors the Android Proxy settings), and using the Desktop version of the mobile website. Weird - but for now it seems to at least be one way to use Messenger on a phone via a proxy connection

**Comment by Countryangel80** [comment]
Well, it is better than nothing. Thank you for taking a look at it and trying to figure it out, it is appreciated!

**Comment by Countryangel80** [comment]
Google Play Store is also not working, I am showing connected to the internet but the Play Store keeps giving the error message "something went wrong try again"

**Comment by pyamsoft** [comment]
Odd, the play store is working fine on my device on a 4G connection, or wifi

I am able to browse and download apps. Maybe your tetherfi device connection is not fast enough or spotty?

**Comment by Countryangel80** [comment]
Should I check the connection speed and see if that is the issue?

**Comment by Countryangel80** [comment]
I did the update within the app yesterday and ever since then I am shown connected yet anytime I try to access anything I am shown no connection

**Comment by pyamsoft** [comment]
Try rebooting your both devices. It sounds like your hosting device connection is just too slow.

Tetherfi as a proxy is about 75% as fast as a direct network connection, so there will be a worse network delay
