### ISSUE TITLE
Wireguard and Tetherfi

### ISSUE THREAD

**Issue by budda85** [pyamsoft/tetherfi#201]
I use wireguard on my cell phone. Now I wanted to use tetherfi to get my laptop on the internet. With wireguard enabled I can't get internet on my laptop. If I turn off wireguard, everything works fine. Is there a possibility to get this working with wireguard? Or maybe openVPN?

**Comment by pyamsoft** [comment]
The answer as with many tech networking things is, well it depends 

My setup works fine using TailScale, which is a Wireguard implementation. But the order of operations is picky here. 

Leave the VPN off, launch the hotspot and confirm its working, then turn the VPN back on. Does it work? Are there options in the Wireguard VPN to allow local sharing, or to bypass for certain IP addresses?

**Comment by budda85** [comment]
Thanks for the hint with the local sharing.
I've added allowed IPs in my Client config and now it is working.

**Comment by killerkalamari** [comment]
I needed to exclude 192.168.49.1, but  I'm generating a QR code of the configuration file using `qrencode -t UTF8 </path/to/conf/file`), so I excluded 192.168.x.x in the Wireguard client configuration to make the AllowedIPs list a lot shorter. Generated via https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/ with the inputs `0.0.0.0/0, ::/0` and `192.168.0.0/16`:

`AllowedIPs = 0.0.0.0/1, 128.0.0.0/2, 192.0.0.0/9, 192.128.0.0/11, 192.160.0.0/13, 192.169.0.0/16, 192.170.0.0/15, 192.172.0.0/14, 192.176.0.0/12, 192.192.0.0/10, 193.0.0.0/8, 194.0.0.0/7, 196.0.0.0/6, 200.0.0.0/5, 208.0.0.0/4, 224.0.0.0/3, ::/0`

Per the instructions above, first activate TetherFi without Wireguard. Once tethered, activate the Wireguard VPN via the Wireguard app on the phone. You can verify that the VPN is working across the tether by going to https://ip.me on the computer. Assuming your VPN is fast enough, it works great to bypass mobile carrier throttling of video streaming. To test your streaming speed, use https://fast.com (2.4Mbps is throttled 480p speed, 5-10 Mbps is 1080p, and 10-15+ Mbps will probably handle 4K).
