### ISSUE TITLE
turn hotspot off after x minutes with no connected clients

### ISSUE THREAD

**Issue by ForbodingAngel** [pyamsoft/tetherfi#203]
Pretty much what the title says. I would like an option to turn off the hotspot if there have been no connected clients for a specified amount of time.

**Comment by pyamsoft** [comment]
I'll see about adding something like this

**Comment by pyamsoft** [comment]
This will be added in the next release as a `Tweak` called `Stop Hotspot With No Clients`, which automatically turns the hotspot off after 10 minutes with no connected client

**Comment by pyamsoft** [comment]
Version 32 is in the Open Testing Beta and will be released publicly on the store within the week.
