### ISSUE TITLE
Allow bypass VPN detectiom

### ISSUE THREAD

**Issue by EmberHeartshine** [pyamsoft/tetherfi#204]
Could there be a toggle to the new VPN detection introduced in c003fe8/release 31? TetherFi works fine for me using Proton on my device, so being able to toggle that check off could be very useful.

**Comment by pyamsoft** [comment]
I can see about adding some kind of checkbox to say "my VPN works"

The blocker dialog was added because there are frequent issues with launching the hotspot when a VPN is running.

Once the hotspot is on though the VPN can be turned back on, it's usually not a problem. Just the initial launch.

**Comment by EmberHeartshine** [comment]
I know, but my phone is set to launch the VPN on boot and internet traffic is blocked if it doesn't go through it. This new manual change breaks that automation.

**Comment by pyamsoft** [comment]
I see, I'll add a bypass in the next release

**Comment by pyamsoft** [comment]
A bypass will be added for the next version as a Tweak. No release date expected yet.

**Comment by pyamsoft** [comment]
Version 32 is in Open Testing Beta in the store and will be released publicly later in the week.
