### ISSUE TITLE
Login to games

### ISSUE THREAD

**Issue by jshrop** [pyamsoft/tetherfi#206]
Not sure if this issue is one already mentioned, but; I’m sharing from an android to an iPhone. Surfing, social media, and streaming movies works great, but for some reason it will not login to my games. I tried to play CarX, and it goes through loading/downloading update, but stops at synchronizing. For some reason it won’t login. Same thing with candy crush, No Limit Drag, and COD. Other than that, this app is awesome. Would love to see an iOS version.

**Comment by pyamsoft** [comment]
Hi

Tldr, Games don't work currently because they use UDP networking.

This is a hard technology problem. There is an open issue tracking a possible solution but to keep a long story short, this will take a very long time. Sorry.

**Comment by jshrop** [comment]
I had a feeling UDP is what the other issuers were talking about. Well man, this app is still awesome none the less. I’d still love to seen an iOS version someday. :]
