### ISSUE TITLE
Steam and Zypper not working

### ISSUE THREAD

**Issue by domglusk** [pyamsoft/tetherfi#208]
Just want to add that both Steam and Zypper (package manager for OpenSUSE) don't work through Tetherfi sadly. Not sure if either can be fixed tho

**Comment by pyamsoft** [comment]
Steam yeah sadly, it both requires UDP and doesn't allow proxy connects as part of its TOS, so its actively hostile

Zypper, I've never used but is there no way to tell it to use http_proxy on the command line? I use arch (btw) and pacman works fine when I specify http_proxy in the environment

**Comment by domglusk** [comment]
Havent tried setting http proxy via environmental variable, I'll let you know if it works or not. Wish steam would work, but understand why it doesn't

**Comment by domglusk** [comment]
Setting the proxy within YaST fixed the issue!
