### ISSUE TITLE
Tetherfi Does Work behind VPN

### ISSUE THREAD

**Issue by domglusk** [pyamsoft/tetherfi#209]
ProtonVPN with auto protocol, in my case it only works the vpn on. Maybe turn the vpn detected block to just a warning?

**Comment by pyamsoft** [comment]
A Tweak option will be released in version 32 (currently in Open Testing Beta in Google Play) which will allow you to bypass the VPN warning.

Turn the switch on under the "Tweaks" section and the VPN dialog will not show when you try to start the Hotspot the next time.
