### ISSUE TITLE
How to connect to xbox series x

### ISSUE THREAD

**Issue by Planeman09** [pyamsoft/tetherfi#214]
I'm having trouble connecting to the Xbox with the app. Can't find a good walk through on YouTube that helps

**Comment by pyamsoft** [comment]
Hi, sorry to hear you're having trouble. I don't expect there to be a YouTube video for this app specifically, but what you will want to look for on YouTube would be something like Xbox Series X HTTP Proxy

I don't have an Xbox to test with so I have no idea if TetherFi would help you here though. Just as a heads up: online gaming will not work yet. You may be able to access the online Store on the console and possibly download games (I can on the Nintendo Switch) but playing online won't work.
