### ISSUE TITLE
Can't connect with FTP

### ISSUE THREAD

**Issue by cmjohannes** [pyamsoft/tetherfi#216]
Greetings. I am not a networking guy so please bear with me. 

I am trying to connect to a server using SFTP. Specifically, I am using WinSCP on my laptop running Windows with this software providing my internet access. 

I have no issues connecting to the server with other connections.  I have read it might be a NAT issue or something that could be resolved with IP tables? (https://superuser.com/questions/456406/how-can-i-access-my-desktop-computer-when-its-tethered-to-my-android-phone)

Also, I noticed that the Ping command in CMDPrompt no longer works.

I love the software and use it frequently. Hopefully someone knows of a way to get S/FTP and SCP working.

**Comment by pyamsoft** [comment]
Hi,

We only deal with HTTP traffic in TetherFi currently. I am also not a dedicated network guy and have no idea if it is even possible to forward proxy FTP.

This is not a full tether, it's just an HTTP proxy, so unfortunately we are limited in how general purpose we can be.

Sounds like TetherFi is the wrong tool for your use case
