### ISSUE TITLE
Orbot compatibility

### ISSUE THREAD

**Issue by HostFat** [pyamsoft/tetherfi#217]
I tried to use TetherFi with Orbot, but it seems not working:

https://github.com/guardianproject/orbot/releases/tag/17.1.0-BETA-3-tor.0.4.7.14

Is it a bug or something that can't be fixed?

**Comment by pyamsoft** [comment]
Hello,

I have no idea what Orbot is or what it does.

Does TetherFi work without Orbot? 

If it does: When Orbot is turned on, what stops working?

**Comment by HostFat** [comment]
1) Starting TetherFi on the first phone
2) Connecting the second phone to the hostpot
3) The second phone is working on Internet
4) Starting Orbot and Tor on the first phone
5) The second phone stops working on internet

Or

1) Starting Orbot and Tor on the first phone
2) Starting TetherFi on the first phone
3) Connecting the second phone to the hostpot
4) The second phone isn't working on Internet

**Comment by pyamsoft** [comment]
Sounds like Orbot is not compatible, probably similar to some VPNs that don't play nice.

I think this is out of my hands unfortunately
