### ISSUE TITLE
Launching TetherFi from quick settings tile hotspot configuration is missing.

### ISSUE THREAD

**Issue by alexusa2002** [pyamsoft/tetherfi#218]
I'm trying to automate when TetherFi launches by using Tasker. The tile under quick settings works very well for automation, but once the app is launched the hotspot configuration is blank. For example, Hotspot Name will say "NO NAME", Password will say "NO PASSWORD", and Proxy/URL will say "NO HOST". Proxy port still shows 8228. If I hit refresh hotspot the configuration eventually shows up, but this defeats the purpose of automating. I'm running Android 13. Thank you!

**Comment by pyamsoft** [comment]
Hi,

I an not quite sure what your setup is here. I've never used Tasker before and can't speak to how it works - does TetherFi work when you are not using Tasker? What stops working when you add Tasked into the mix?

**Comment by alexusa2002** [comment]
Hi,

I'm using TetherFi to share my phone's Internet connection with the Android based radio unit in my car. With Tasker I can create an automation that launches TetherFi when my phone connects with the radio's Bluetooth. Launching the main TetherFi app I still have to manually press "Start TetherFi Hotspot", but Tasker allows me to use the TetherFi quicklaunch tile instead. With the tile I don't have to press "Start TetherFi Hotspot", which allows to automate launching the hotspot without any user interaction.

Removing Tasker from this scenario, I still have the same problem. Most of the time when I manually launch TetherFi from the quick settings tile, the hotspot configuration is not present. The hotspot will start, but not the proxy. Also, the configuration settings are not set. I have to press refresh hotspot. I'm attaching a screenshot.

Thank you!
![Screenshot_20230920-210117](https://github.com/pyamsoft/tetherfi/assets/57840500/407fe26a-e33f-44b9-9ca4-62beef295c6c)

**Comment by pyamsoft** [comment]
I've reproduced the bug and will look at getting it fixed. Thanks for the report!

**Comment by pyamsoft** [comment]
I believe I've fixed the bug in the latest development version. No estimated date for the next release build, but the next update should have this issue fixed.

**Comment by pyamsoft** [comment]
Hello, a new build (34) has been uploaded to the Open Testing track on Google play, and uploaded as a release on Github. Public release will happen later in the week. Please see if this new build fixes the issue for you, thanks!

**Comment by alexusa2002** [comment]
Thank you! I'll report back once I upgrade to the new version.

**Comment by pyamsoft** [comment]
Version 34 should be live on the store.
