### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by git5loxosec** [pyamsoft/tetherfi#220]
Make a video tutorial, the main issue with this project is the lack of documentation available, FYI there's already a company called Tetherfi so whenever anyone try to look up on the internet for help those people shows up, I've been trying to make it work on kali using proxychains plus all "instructions" provided  with no luck at all. Method Android + Kali Linux/xfce

**Comment by pyamsoft** [comment]
Hi,

I'll think about a better way to convey the setup steps, but right now don't have the spare time to record anything useful.

You shouldn't need proxychains, as that is a transparent setup. I'm not even sure if proxychains transparent would work in this case, as TetherFi is an explicit proxy that relies on HTTP CONNECT to be passed through.

You should just be able to export  environment variables - see the Wiki for some common setups.
