### ISSUE TITLE
TetherFi will not start despite all conditions being met

### ISSUE THREAD

**Issue by audiodef** [pyamsoft/tetherfi#222]
All of these conditions were met:
Wifi is on
Wifi is not connected to anything
Wifi was restarted 
Hotspot pass is >= 8 chars (tried changing it)
Hotspot name is unique (tried changing it)

But TetherFi shows me an err dialog asking me to check these items.

**Comment by pyamsoft** [comment]
Hello

It could be a number of things - worst case, your device does not support the functions needed.

Let's troubleshoot it together though.

What device are you using? What version of Android, if you know?

1. Reset the app settings to default. The defaults should work on a supported device. Click the settings gear on the top right, scroll down to the Danger  Zone section and click Reset All Settings. Restart the app, and just click the start button, do not customize anything. Check if this works.

If it does, great!

2. If not, reboot your device. Android is finnicky and can have weird Wifi problems.

Let me know if 1 or 2 worked for you!

**Comment by pyamsoft** [comment]
Also, what is the error text in the Broadcast Status? It should say something like "Failed to created network"

A screenshot would help!

**Comment by audiodef** [comment]
Thanks for replying. :)

Neither 1 nor 2 worked, sadly. I'm using a Samsung Galaxy S10e. If it
matters, my carrier is AT&T.

**Comment by pyamsoft** [comment]
Please include a screenshot of the Hotspot screen AFTER you dismiss the error dialog. It should include red error text under the Broadcast Status section, thanks!

**Comment by zzxx53** [comment]
Do you have location services turned on? This tripped me up once.

**Comment by audiodef** [comment]
Hi!

I'm so sorry for taking so long. Attached is a screenshot. I've done all
the things mentioned in the error message.

**Comment by pyamsoft** [comment]
Hi there, looks like Github ate your screenshot - could you try again?

Also please make sure you are on the latest version of the app, which is 36 at the time of writing.

**Comment by ItsIgnacioPortal** [comment]
The screenshot didn't post. Could you try again?

**Comment by pyamsoft** [comment]
Recent changes with version 38 may have improved this situation.

Could you try again with the new 38?

**Comment by audiodef** [comment]
Sure! Gave it a try, still a no go for me. I'm guessing my particular
device (Samsung Galaxy S10e) isn't compatible.

I'd be glad to give it another go whenever I upgrade my phone. Thanks for
making such a cool app and being super nice. :)

**Comment by pyamsoft** [comment]
Sad to hear, but I suppose that's just the nature of the beast sometimes. Wishing you all the best, thank you for reporting!

**Comment by pyamsoft** [comment]
Sorry, just one more curiosity

In your device system settings, do you have a Wifi Direct option?

On my device it's found under Wifi through the 3-dot menu, but it should also show up with a search
