### ISSUE TITLE
Spotify says offline

### ISSUE THREAD

**Issue by enigma-py** [pyamsoft/tetherfi#226]
Using other phone for Spotify because audio quality is better but I had to group it with my phone that I'm tethering the connection from that also a Spotify on it so you'll have to group the devices I believe the play because even if you tether the connection it says Spotify is unavailable on the other device that I want to play from.

**Comment by pyamsoft** [comment]
Not too sure I understand your setup exactly , but this is the second report of Spotify issues, it may not be supported on the hotspot sadly

**Comment by pyamsoft** [comment]
Closing for now, Spotify is sadly incompatible currently as it does not like proxy services like our hotspot.
