### ISSUE TITLE
User id crash

### ISSUE THREAD

**Issue by PeterKW** [pyamsoft/tetherfi#229]
User 11 not 10 when signed in as guest user on Android

![Screenshot_20231019-095205.png](https://github.com/pyamsoft/tetherfi/assets/13779157/f366414e-83a9-4ebf-9443-c91112764765)

**Comment by pyamsoft** [comment]
Very odd

This is a crash in the system level Tile service (the quick tile in  the notification drop down)

I don't control that code since its part of the operating system. Not sure what we can fix here.

Do you still get the crash even if you do not use the quick tile?

**Comment by pyamsoft** [comment]
Ah I see your comment about being signed in as a guest.

I assume this is an Android OS thing, if you are not the user that installed the app.

Honestly I've never dealt with multi user setups on Android. I assume you added the tile as a Non Guest user and are attempting to use it as a Guest.

What if you add the Tile as the Guest User first?

**Comment by pyamsoft** [comment]
Does this still happen on the newly released version 38?
