### ISSUE TITLE
Pixel 7 on Android 14 does not properly share internet with connected devices

### ISSUE THREAD

**Issue by IGGUS** [pyamsoft/tetherfi#230]
Initial app setup on Pixel 7 Android 14 host device was a breeze.  Configured options in app and left most as defaults, such as proxy port. Allowed OS/device permissions as required.  Then enabled hotspot. 

Client device (Samsung Note 9) quickly found host wifi hotspot network. It received DHCP IP as expected based on the host Tetherfi config.  Samsung Android reporting nearly 1Gbps strong signal - 46 dBm connection.  However client Android showing status of "Connected without internet" generic message and I'm unable to access WAN.

Please help, as it's imagine I'm not the only Pixel 7 user who'd love an alternative to the built in Hotspot feature which, while it does allow clients such as my Note 9 to successfully connect and share internet:

> Does not allow me to see which devices are connected to my host hotspot or manage them! C'mon Google, get it together...
> Allows my carrier to throttle my traffic (illegal where I live yet they do it anyway) when they see certain traffic going through while phone operating in hotspot mode.

Happy the help troubleshoot, provide logs or help with whatever tech support you need to get this working - thanks!

**Comment by pyamsoft** [comment]
Hi

You need to configure the Client sounds like. Make sure that in the Network Settings on the Note 9, that you have enabled the HTTP Proxy as well.

Please note that on Android, the only apps that are guaranteed to respect the proxy setting by the OS, is the default web browser.

**Comment by pyamsoft** [comment]
This may be affected by #250

**Comment by pyamsoft** [comment]
Recent changes to version 38 on the Play Store may have resolved some networking issues reported by Pixel devices. Can you try again and see if 38 has improved your situation?
