### ISSUE TITLE
Tethering via RNDIS instead of Wi-Fi hotspot?

### ISSUE THREAD

**Issue by brlin-tw** [pyamsoft/tetherfi#232]
Hello, I would like to ask whether I can start a proxy service _without_ launching the Wi-Fi hotspot?

I'm currently using the following configuration:

* "Bind Proxy to All Interfaces" option toggled
* Connect the phone to PC, then enabled USB tethering
* Use the gateway address of USB tethering as the proxy server host address

While it works as expected,  I do not want the Wi-Fi radio also powered without any purpose and unnecessarily generates heat, can I switch it off or there's another application that is more fit  for my usecase?

Thanks in advance!

**Comment by pyamsoft** [comment]
Right now, the Wifi radio is a required component. Maybe in the future I could support this, but currently its not supported officially over USB tether

**Comment by Theone2626** [comment]
No connection

**Comment by Theone2626** [comment]
No connection

**Comment by Arr4y** [comment]
> Hello, I would like to ask whether I can start a proxy service _without_ launching the Wi-Fi hotspot?
> 
> I'm currently using the following configuration:
> 
>     * "Bind Proxy to All Interfaces" option toggled
> 
>     * Connect the phone to PC, then enabled USB tethering
> 
>     * Use the gateway address of USB tethering as the proxy server host address
> 
> 
> While it works as expected, I do not want the Wi-Fi radio also powered without any purpose and unnecessarily generates heat, can I switch it off or there's another application that is more fit for my usecase?
> 
> Thanks in advance!

This place isn't for applications like these but I can help you. When you plug in your phone through USB, you can set it up as a tether. Then it will give your device a local IP address.

On your phone, install a proxy server app (not client) and run it under your local IP (your pc refers to your phone as the host IP address just like it lists your router "192.168.0.1 or 192.168.1.1" but it is under a diffrent local IP).

Once you have that server running on your phone, on your PC connect to that proxy server (either through your computer's HTTP in settings or a custom client if you're not using HTTP). After that, everything will work perfect.

**Comment by pyamsoft** [comment]
Hi, thanks for the advice

For reference, here's the mind roadmap for this feature

Add UI to allow specifying a host RNDIS IP address by hand
If host IP is specified, launch the proxy directly instead of going through the WiFi direct process.

From when this ticket was originally opened, the proxy server is now completely standalone, so it should be possible to implement this feature once I am done with the work to migrate off of old wake lock code.

I hope to have this in either 48, or 49, but until then, you may continue using your current preferred method.

**Comment by pyamsoft** [comment]
I am testing a Dev version with support for proxying over an RNDIS connection without requiring WiFi direct or the wireless radio to be on.

I hope to have this tested enough to release in the next version, 48.

**Comment by pyamsoft** [comment]
This has been implemented in version 49, which is now in beta testing and will hopefully be released fully later this week.
