### ISSUE TITLE
[Feature Request] Undetectable Hotspot

### ISSUE THREAD

**Issue by TorCzaf** [pyamsoft/tetherfi#233]
Hi can you add an option to hide Hotspot name from Wi-Fi list/page while Hotspot is running?

I mean I would expose my Hotspot for those who want to use it and when they connect, I hide it so others don't know or suspect that I run Hotspot.
Thank You.

**Comment by pyamsoft** [comment]
Hi

Given that the broadcast piece of the hot spot is powered by wifi direct, this is not possible at this time, sorry.
