### ISSUE TITLE
Applications 

### ISSUE THREAD

**Issue by Mohadm58** [pyamsoft/tetherfi#235]
You said they cannot run applications like Messenger and Telegram. There is a way for me to run these applications through Super Proxy. It does it for me. I wrote 192.168.49.1:8228 and this is how all the applications work. No, which she said does not work..... She tried a special application for me, but no.  Works well

I want you to modify this application and develop it through reverse engineering
![Uploading IMG_20231029_131248.jpg…]()

**Comment by pyamsoft** [comment]
Hi

SuperProxy is a cool app!
Super proxy is a VPN app. That is why it is able to see connections we can not.

TetherFi is not a VPN app, and I do not have plans to change this. You can still user SuperProxy with TetherFi by using the VPN tweak.

You would run TetherFi on the Server device and run SuperProxy on your Client device. UDP connections and games would still not work, as there is no way currently to proxy UDP traffic transparently.
