### ISSUE TITLE
Is it posible to start on boot or to start via Intent?

### ISSUE THREAD

**Issue by hkfuertes** [pyamsoft/tetherfi#236]
I would like to run a hotspot (no need for proxy, local only) on a device that does not have AP (Android TV Stick), and that has no battery. I would like for an app that I'm developing to start the hotspot on boot. Is there any toggle to auto enable it on boot?

I can create a simple app with a bootreceiver and trigger a intent to enable the hotspot... is it posible to do that?

Thank you!

**Comment by pyamsoft** [comment]
Hi

This doesn't seem like a question related to TetherFi, but rather a general development question. I prefer Issues to be for bugs and requests only. 

From what you describe it sounds perfectly possible to write an app which does this.

**Comment by hkfuertes** [comment]
My question was not if it is possible or not, but if you already provide a mechanism to auto start the hotspot on boot or a way to start it via intent...

**Comment by pyamsoft** [comment]
Oh I see

No I do not provide an intent based way to start the hotspot, and for security related reasons I do not plan to, sorry.
