### ISSUE TITLE
it never connects in iPad. 

### ISSUE THREAD

**Issue by KarkanAlzwayed** [pyamsoft/tetherfi#248]
I have configured the proxy to manual where it makes me enter the "sever" and the port. Did` 192.168.49.1 `in the server, and port` 8000 `and port` 8228 `, turned wi-fi off and on, still nothing. Tried with automatic proxy where it only lets me enter the "URL", same thing. Is this a known thing or is just apple being apple? iPad is 9th Gen and is on the latest software.

**Comment by pyamsoft** [comment]
Hi,

Send please a screenshot of your TetherFi Hotspot screen, and make sure the port and server numbers match on your iPad

Sometimes, rebooting the Android device or the iPad can also help

**Comment by KarkanAlzwayed** [comment]
Here is a screenshot. I'll try rebooting both and see 
![Screenshot_20231211_181452_TetherFi](https://github.com/pyamsoft/tetherfi/assets/49320606/39647981-7ec6-44d4-bb40-663876e73b7a)

**Comment by KarkanAlzwayed** [comment]
Rebooting both worked. Is this mentioned in the readme? If it is, my apologies for not reading. If need, then I'd definitely add it. Thank you for the prompt response

**Comment by pyamsoft** [comment]
No only because this is "just Android things" so its not like a consistent fix. Glad to hear its working!
