### ISSUE TITLE
The QR code isn't scannable when using the dark UI theme

### ISSUE THREAD

**Issue by brlin-tw** [pyamsoft/tetherfi#251]
I am unable to scan the QR code using QtQR(which uses the open-source [ZBar bar code reader](https://zbar.sourceforge.net/) for scanning) when the dark UI  theme is used:

![Screenshot of scanning the QR code using QtQR when the dark UI theme is used, notice that the border of the QR code is barely visible due to the low contrast of color](https://github.com/pyamsoft/tetherfi/assets/13408130/bb110806-3fac-4138-95fb-6349e7325308 "Screenshot of scanning the QR code using QtQR when the dark UI theme is used, notice that the border of the QR code is barely visible due to the low contrast of color")

When the light UI theme is used, the QR code can be scanned in an instant, so it's not an issue with the glare of the screen itself.

I believe this is due to the QR code itself lacking a white border(i.e. "quiet zone") required by the QR code specification to allow the decoding algorithm to detect its presence.

> The 'Quiet Zone' is an essential part of every QR code. A white space border frames the QR code, separating it from other visual noise surrounding it. The purpose of a 'Quiet Zone' is clear: it signals the beginning and end of the QR code to scanners, helping them identify and accurately interpret the code.
> 
>> Source: [Importance of Having a 'Quiet Zone' Around Your QR Code | The Ultimate QR Code Size Guide for Optimal Scanning](https://qrcodedynamic.com/blog/qr-code-size/#importance-of-having-a-quiet-zone-around-your-qr-code)

According to [How Much White Space Do You Need Around a QR Code? | The Ultimate QR Code Size Guide for Optimal Scanning](https://qrcodedynamic.com/blog/qr-code-size/#how-much-white-space-do-you-need-around-a-qr-code), the 'Quiet Zone' should be at least four modules wide on all four sides of the QR code(A 'module' in this context refers to the smallest square unit that makes up the QR code).

**Comment by brlin-tw** [comment]
Another screenshot, but captured in full color instead of grayscale: 
![2023-12-14-135722](https://github.com/pyamsoft/tetherfi/assets/13408130/7090b01d-476e-4831-b7bc-b0e5b9469190)

**Comment by pyamsoft** [comment]
Gotcha, I'll add a white quiet zone border for the next release 39, thanks!

**Comment by pyamsoft** [comment]
I will be able to address this hopefully by the middle of next week with a 39 release. Thank you for your patience, for the time being using Light mode seems to fix the problem as you stated, so that is the recommended work around.

**Comment by pyamsoft** [comment]
39 is in open beta on the store and includes the QR code quiet zone

**Comment by pyamsoft** [comment]
39 is released, hopefully this fixed your bug! Thank you for your report!

**Comment by brlin-tw** [comment]
Yes, I can successfully scan the QR code now, thanks!

An additional thought would be whether simply invert the color of the QR code(black to white) would also solve this issue, but it not matter much anyway.
