### ISSUE TITLE
Windows Command Line Tools

### ISSUE THREAD

**Issue by Aggie85** [pyamsoft/tetherfi#253]
Howdy!

I am not sure if this is one of those incompatibility or ignorance setup errors on my part.

I am trying to use this with my Flutter development machine and every tool that runs with a command line (even ping) cannot resolve an url address (I.e. dns isn't working). If I do the 'dns' manually and type in ping <ip_address> it works fine.

Is there away to get DNS working on Windows apps other than the browser)?

All the best and thanks for a great product!

Aggie85

**Comment by pyamsoft** [comment]
If you follow the Windows connection instructions on the wiki do things start working?

ping won't work because its a different "internet language" called ICMP, and the TetherFi proxy only speaks HTTP

Command line tools may need a special windows specific environment variable, but I'm sadly not sure what it is, sorry.

**Comment by Aggie85** [comment]
Browsing works great ... everything else not at all! 

I am guessing it is just the nature of the beast. I was hoping this would resolve my data issues. 

I can hand my IPad to my granddaughter and she can watch a TB of videos in a month and AT&T doesn't care ... I as a software developer am limited to 50GB of hotspot data which is a couple of Windows updates (I live where I cannot get highspeed internet without going into town for my purposes)!

Any how, you have a very nice product.

All the best,

Aggie85

**Comment by pyamsoft** [comment]
Ah yes in that case unfortunately I don't know how much this will be able to assist you currently.

Having a software background, hopefully I can be a little technical. TetherFi is a wifi direct access point backed by an HTTP proxy server. On Android we are only able to intercept TCP based http traffic - native apps like Netflix for example would likely use websockets or QUIC based delivery, which Android does not let us monitor or forward currently.

Sadly, the app is best served for browser related tasks, as right now mobile OS's only guarantee that the browser app respects proxy settings.

Sadly I don't think this app is the right tool for the job. You may have more success with local VPN apps that forward you to full proxies. TetherFi has no plans to become a local VPN style app.

**Comment by Aggie85** [comment]
Thanks for the detailed information - I really wasn't thinking when I saw this "as a" solution but to be honest, it is still a very useful app.

I don't think I have seen any VPNs running on Android that allow users to bypass the mobile hotspot for data access. I will look into that more.

All the best & before I forget, MERRY CHRISTMAS & HAPPY NEW YEAR!

Aggie85

**Comment by pyamsoft** [comment]
Thanks, to you too!
