### ISSUE TITLE
Does It Work On Xbox One?

### ISSUE THREAD

**Issue by TheLovelyGayRat** [pyamsoft/tetherfi#271]
And How?

**Comment by pyamsoft** [comment]
Hi!

I'm not sure given that I do not own an Xbox, but I know we have issues on PS4 connecting to the Playstation Store. Note that even if the app does work on Xbox, you won't be able to play online games so it's not too useful right now :(

**Comment by TheLovelyGayRat** [comment]
> Hi!
> 
> I'm not sure given that I do not own an Xbox, but I know we have issues on PS4 connecting to the Playstation Store. Note that even if the app does work on Xbox, you won't be able to play online games so it's not too useful right now :(

Oh Okay, Thanks Anyway. And Have A Good Day/Night.

**Comment by pyamsoft** [comment]
Thank you!
