### ISSUE TITLE
Ability to have option to stay connected to Wifi Network but Cellular is used for internet 

### ISSUE THREAD

**Issue by 7eventech77** [pyamsoft/tetherfi#272]
I just found TetherFi and are enjoying it but was also looking at other apps and found this one called "NetShare" and it is almost identical to TetherFi in features except for the "Bind to Mobile Data" feature. This feature allows the hotspot app to use Mobile Data instead of WiFi if you are connected to a Wireless Network as well and don't want to disable "auto reconnect" for when the internet comes back on. The feature works well on NetShare which also uses the same "proxy" functionality. I tested TetherFi to see if I could get this functionality to work somehow but could not. I have read that WiFi must enabled for TetherFi to work so I am not asking if you can disable that and have it work, merely to have an option as described above to still be connected to a WiFi network and TetherFi turns Mobile Data on and uses that.

Thank you in advance! I would rather use and support an open source alternative than a proprietary one that uses ads model and will cost me $7.99 to turn them off.

**Comment by pyamsoft** [comment]
As an aside,

TetherFi was directly inspired by NetShare! I was a NetShare user, but I am also a coder and got the "itch" to build my own tool to solve the same problem.

A few months later, and here we are! I will update this issue as the binding network feature moves closer in scope.

**Comment by pyamsoft** [comment]
Hello

Please see progress in #154

**Comment by 7eventech77** [comment]
Thank you!
