### ISSUE TITLE
Insufficient ram memory 

### ISSUE THREAD

**Issue by ExGon** [pyamsoft/tetherfi#273]
I am a user with a phone with low memory RAM, when I activate the application it sometimes closes, and when I try to activate it from the notification bar widget I have to Open the application to remove that message. I would like to be able to activate the app again from the notification bar, skipping the error notification.

**Comment by bldg-peter** [comment]
Hi,

How low is the ram?

Due to some weird Android OS quirks, the app only works if it launches from the main screen.

It doesn't seem very logical but I have observed this to be the case on many devices, which is why the notification is intentionally not able to launch the hotspot

**Comment by pyamsoft** [comment]
Hi,

How low is the ram?

Due to some weird Android OS quirks, the app only works if it launches from the main screen.

It doesn't seem very logical but I have observed this to be the case on many devices, which is why the notification is intentionally not able to launch the hotspot

**Comment by ExGon** [comment]
I have 2 GB of ram. Yes, I get an error notification when I try to activate it again from the notification bar widget, 
That can't be changed? That the app can be activated again even if it has been forcefully closed?. (PD: I'm poor, I don't have money for a more expensive phone)

**Comment by pyamsoft** [comment]
No unfortunate the app is very minimal as it is when using the hotspot. If your device is running out of memory, then short of rewriting the entire thing there is very little I can do for a device with only 2gigs of memory, sorry
