### ISSUE TITLE
Destination Host Unreachable

### ISSUE THREAD

**Issue by wspvlv** [pyamsoft/tetherfi#277]
What I've tried to do is to share my - mobile connection using this app. I have configured the proxy on the CLI (Linux) however when I ping I get
```sh
From 192.168.49.1 icmp_seq=1 Destination Net Unreachable
```
What do I do?

**Comment by pyamsoft** [comment]
Hi, not sure you're able to ping the Android actually - we set up an HTTP server, and Wi-Fi direct gives us simple DHCP, but nothing speaks ICMP as far as I know.

For CLI usage, I use [this script from my dotfiles](https://github.com/pyamsoft/dots/blob/main/bin/apply-http-proxy), see if that works for you?

Use it like:
```bash
$ apply-http-proxy default # To see what it will be doing
$ eval "$(apply-http-proxy default)" # To execute
```

**Comment by wspvlv** [comment]
Hello, I tried the script. I can ping my phone back
```
4 bytes from 192.168.49.1: icmp_seq=1 ttl=64 time=5.29 ms
```
However, pinging an address outside the private area leads to the same issue.
```
From 192.168.49.1 icmp_seq=1 Destination Net Unreachable
```
I assume pings from the terminal don't require a specific proxy setup

**Comment by pyamsoft** [comment]
Sorry, maybe my previous content wasn't clear

Using the Proxy, ping will not work. We only proxy http TCP traffic, not ICMP.

You would be able to use the script and then use something like curl which speaks HTTP, but not ping.

**Comment by wspvlv** [comment]
Ohh, I see. I set up the proxy for Firefox, and it does indeed work. Thanks for the help! Sorry, for wasting your time

**Comment by pyamsoft** [comment]
Glad to hear it worked, have a good one!
