### ISSUE TITLE
Inconsistent HTTP request response on Linux software repository mirrors when using vs. not-using TetherFi

### ISSUE THREAD

**Issue by brlin-tw** [pyamsoft/tetherfi#280]
I recently found that using TetherFi to fetch specific resources from some Linux distribution software archives (mirrors) will generate spurious HTTP 404 Not found errors:

```output
brlin@brlin-fw13:~$ sudo docker run --env http_proxy --env https_proxy --rm -it centos:7
[root@abbda6318740 /]# yum makecache
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: centos.ccns.ncku.edu.tw
 * extras: centos.ccns.ncku.edu.tw
 * updates: centos.ccns.ncku.edu.tw
http://centos.ccns.ncku.edu.tw/centos/7.9.2009/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.

   ...stripped...

failure: repodata/repomd.xml from base: [Errno 256] No more mirrors to try.
http://centos.ccns.ncku.edu.tw/centos/7.9.2009/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://ftp.ksu.edu.tw/pub/CentOS/7.9.2009/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://ftp.sjtu.edu.cn/centos/7.9.2009/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found

   ...stripped...

http://mirrors.cqu.edu.cn/CentOS/7.9.2009/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://mirrors.qlu.edu.cn/centos/7.9.2009/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://mirrors.ustc.edu.cn/centos/7.9.2009/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
```

I originally thought that it was the ISP who implemented faulty transparent proxies in between the connection that caches the erratic response however the problem is no longer reproduced after I unset the proxy settings and use the native USB tethering network sharing:

```output
[root@abbda6318740 /]# unset http_proxy https_proxy
[root@abbda6318740 /]# yum makecache
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: centos.ccns.ncku.edu.tw
 * extras: centos.ccns.ncku.edu.tw
 * updates: centos.ccns.ncku.edu.tw
base                                                                                                | 3.6 kB  00:00:00     
extras                                                                                              | 2.9 kB  00:00:00     
updates                                                                                             | 2.9 kB  00:00:00     
(1/10): base/7/x86_64/group_gz                                                                      | 153 kB  00:00:00     
(2/10): extras/7/x86_64/filelists_db                                                                | 303 kB  00:00:00     
(3/10): extras/7/x86_64/other_db                                                                    | 150 kB  00:00:00     
(4/10): extras/7/x86_64/primary_db                                                                  | 250 kB  00:00:00     
(5/10): base/7/x86_64/other_db                                                                      | 2.6 MB  00:00:01     
(6/10): updates/7/x86_64/other_db                                                                   | 1.5 MB  00:00:01     
(7/10): base/7/x86_64/filelists_db                                                                  | 7.2 MB  00:00:02     
(8/10): updates/7/x86_64/filelists_db                                                               |  14 MB  00:00:03     
(9/10): base/7/x86_64/primary_db                                                                    | 6.1 MB  00:00:06     
(10/10): updates/7/x86_64/primary_db                                                                |  25 MB  00:00:21     
Metadata Cache Created
```

The issue can also be reproduced when I use the web browser to access the same URL(left: w/o TetherFi; right: w/ TetherFi):

![Screenshot of the comparison of the HTTP request and responses](https://github.com/pyamsoft/tetherfi/assets/13408130/31c418c5-c4c9-4950-8f35-75818eae1d54 "Screenshot of the comparison of the HTTP request and responses")

I wonder whether there's any difference in the HTTP requests that are generated w/, w/o TetherFi that may trigger the different result?

**Comment by brlin-tw** [comment]
Debug log with excess "Proxy Request" lines stripped: [debug.txt](https://github.com/pyamsoft/tetherfi/files/14609005/debug.txt)

**Comment by pyamsoft** [comment]
I will look. TetherFi generally speaking does not change requests, but this may be sending extra data over as part of the HTTP connect step.

I will attempt to reproduce the issue on my end first.

**Comment by pyamsoft** [comment]
Hi,

Testing against this URL: https://mirror01.idc.hinet.net/centos/7.9.2009/os/x86_64/repodata/repomd.xml
using Firefox 123 on ArchLinux and MacOS, I was not able to recreate the 404.

While the page certainly loads slightly slower because of the proxy, I was able to get the XML file to load using both the latest main branch and the release build 40

Are you consistently able to reproduce the 404? Could there be something else at play like the server blocking an IP address, or some network configuration on your Android device preventing the connection?

**Comment by brlin-tw** [comment]
@pyamsoft 

First of all, apologies for the ignorance.

> Are you consistently able to reproduce the 404?

Mostly yes, there is a minor case where the download will temporarily succeed after several refresh attempts on the web browser, however, most access does return 404.

> Could there be something else at play like the server blocking an IP address

Nothing I would know of.

> some network configuration on your Android device preventing the connection?

Not something I can think of.

**Comment by pyamsoft** [comment]
Are you sure that `yum` in the container is using the http_proxy variables, and that the proxy is set?

If you `curl` the file outside of docker (with the proxy env set) does it work?

trying to isolate if this is a "docker network namespace" thing, or a "proxy http in the terminal" thing, thanks!

**Comment by brlin-tw** [comment]
@pyamsoft 

> Are you sure that `yum` in the container is using the http_proxy variables, and that the proxy is set?

Absolutely.

> If you `curl` the file outside of docker (with the proxy env set) does it work?

Nope:

![Screenshot](https://github.com/pyamsoft/tetherfi/assets/13408130/fcd612d5-3089-4f82-bdb4-3da2aac3676e)

**Comment by brlin-tw** [comment]
I have manually built and installed version 41 from the source, and the problem is no longer reproduced.

Not sure what exactly fixes the issue, though, will it be helpful if I do a git bisect to locate the revision that changes the result?

**Comment by brlin-tw** [comment]
All the HTTP requests that can reproduce the problem using the old version:

* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/geoclue-2.0/geoclue-2.0_2.7.0-3ubuntu3_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/libg/libgee-0.8/gir1.2-gee-0.8_0.20.6-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/geoclue-2.0/gir1.2-geoclue-2.0_2.7.0-3ubuntu3_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/gir1.2-gst-plugins-base-1.0_1.22.6-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gstreamer1.0/gir1.2-gstreamer-1.0_1.22.5-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gtk%2b3.0/gir1.2-gtk-3.0_3.24.38-5ubuntu1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/p/pango1.0/gir1.2-pango-1.0_1.51.0%2bds-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/libs/libsoup2.4/gir1.2-soup-2.4_2.74.3-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/v/vte2.91/gir1.2-vte-2.91_0.74.0-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/gstreamer1.0-alsa_1.22.6-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/c/clutter-gst-3.0/gstreamer1.0-clutter-3.0_3.0.27-3_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/gstreamer1.0-gl_1.22.6-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-good1.0/gstreamer1.0-gtk3_1.22.6-1ubuntu1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/g/gst-libav1.0/gstreamer1.0-libav_1.22.5-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/gstreamer1.0-plugins-base_1.22.6-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/gstreamer1.0-plugins-base_1.22.6-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/gstreamer1.0-plugins-base-apps_1.22.6-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-good1.0/gstreamer1.0-plugins-good_1.22.6-1ubuntu1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-good1.0/gstreamer1.0-plugins-good_1.22.6-1ubuntu1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/g/gst-plugins-ugly1.0/gstreamer1.0-plugins-ugly_1.22.5-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/g/gst-plugins-good1.0/gstreamer1.0-pulseaudio_1.22.6-1ubuntu1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gstreamer1.0/gstreamer1.0-tools_1.22.5-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/gstreamer1.0-x_1.22.6-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/gstreamer1.0-x_1.22.6-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gtk%2b3.0/gtk-update-icon-cache_3.24.38-5ubuntu1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/guile-3.0/guile-3.0-libs_3.0.8-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/a/atkmm1.6/libatkmm-1.6-1v5_2.28.3-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/b/boost1.74/libboost-filesystem1.74.0_1.74.0%2bds1-22ubuntu1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/b/boost1.74/libboost-iostreams1.74.0_1.74.0%2bds1-22ubuntu1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/b/boost1.74/libboost-locale1.74.0_1.74.0%2bds1-22ubuntu1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/b/boost1.74/libboost-regex1.74.0_1.74.0%2bds1-22ubuntu1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/b/boost1.74/libboost-thread1.74.0_1.74.0%2bds1-22ubuntu1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/c/cairomm1.16/libcairomm-1.16-1_1.16.2-7_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/c/clutter-1.0/libclutter-1.0-0_1.26.4%2bgit2779b932%2bdfsg-5_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/c/clutter-gst-3.0/libclutter-gst-3.0-0_3.0.27-3_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/d/db5.3/libdb5.3_5.3.28%2bdfsg2-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/d/db5.3/libdb5.3_5.3.28%2bdfsg2-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/libg/libgee-0.8/libgee-0.8-2_0.20.6-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/geoclue-2.0/libgeoclue-2-0_2.7.0-3ubuntu3_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/glib2.0/libglib2.0-0_2.78.0-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/glib2.0/libglib2.0-0_2.78.0-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/glib2.0/libglib2.0-bin_2.78.0-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/glib2.0/libglib2.0-dev-bin_2.78.0-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/glibmm2.4/libglibmm-2.4-1v5_2.66.6-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/glibmm2.68/libglibmm-2.68-1_2.78.0-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gpgme1.0/libgpgme11_1.18.0-3ubuntu2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gpgme1.0/libgpgmepp6_1.18.0-3ubuntu2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/libgstreamer-gl1.0-0_1.22.6-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/libgstreamer-plugins-base1.0-0_1.22.6-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/libgstreamer-plugins-base1.0-0_1.22.6-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-good1.0/libgstreamer-plugins-good1.0-0_1.22.6-1ubuntu1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gst-plugins-good1.0/libgstreamer-plugins-good1.0-0_1.22.6-1ubuntu1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gstreamer1.0/libgstreamer1.0-0_1.22.5-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gstreamer1.0/libgstreamer1.0-0_1.22.5-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gtk%2b3.0/libgtk-3-0_3.24.38-5ubuntu1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gtk%2b3.0/libgtk-3-bin_3.24.38-5ubuntu1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gtkmm3.0/libgtkmm-3.0-1v5_3.24.8-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gtkmm4.0/libgtkmm-4.0-0_4.10.0-4_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/k/keybinder-3.0/libkeybinder-3.0-0_0.3.2-1.1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/l/lua5.2/liblua5.2-0_5.2.4-3_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/l/lua5.3/liblua5.3-0_5.3.6-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/l/lua5.4/liblua5.4-0_5.4.6-0ubuntu2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/n/netplan.io/libnetplan0_0.107-5ubuntu0.2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/p/pango1.0/libpango-1.0-0_1.51.0%2bds-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/p/pango1.0/libpango-1.0-0_1.51.0%2bds-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/p/pango1.0/libpangocairo-1.0-0_1.51.0%2bds-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/p/pango1.0/libpangocairo-1.0-0_1.51.0%2bds-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/p/pango1.0/libpangoft2-1.0-0_1.51.0%2bds-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/p/pango1.0/libpangoft2-1.0-0_1.51.0%2bds-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/p/pangomm2.48/libpangomm-2.48-1_2.50.1-5_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/p/pango1.0/libpangoxft-1.0-0_1.51.0%2bds-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/libp/libpng1.6/libpng-tools_1.6.40-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/libp/libpng1.6/libpng16-16_1.6.40-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/libp/libpng1.6/libpng16-16_1.6.40-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/p/python3.11/libpython3.11_3.11.6-3_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/p/python3.11/libpython3.11-minimal_3.11.6-3_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/p/python3.11/libpython3.11-stdlib_3.11.6-3_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/g/gpgme1.0/libqgpgme15_1.18.0-3ubuntu2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/r/ruby3.1/libruby3.1_3.1.2-7ubuntu3.1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/s/sdl-ttf2.0/libsdl-ttf2.0-0_2.0.11-6_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/libs/libsigc%2b%2b-2.0/libsigc%2b%2b-2.0-0v5_2.12.0-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/libs/libsigc%2b%2b-3.0/libsigc%2b%2b-3.0-0_3.4.0-7_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/libs/libsoup2.4/libsoup-gnome2.4-1_2.74.3-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/libs/libsoup2.4/libsoup2.4-1_2.74.3-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/libs/libsoup2.4/libsoup2.4-1_2.74.3-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/t/tcl8.6/libtcl8.6_8.6.13%2bdfsg-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/t/tk8.6/libtk8.6_8.6.13-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/libu/libusb-1.0/libusb-1.0-0_1.0.26-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/libu/libusb-1.0/libusb-1.0-0_1.0.26-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/v/vte2.91/libvte-2.91-0_0.74.0-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/v/vte2.91/libvte-2.91-common_0.74.0-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/w/wxwidgets3.2/libwxbase3.2-1_3.2.2%2bdfsg-4_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/w/wxwidgets3.2/libwxgtk-gl3.2-1_3.2.2%2bdfsg-4_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/w/wxwidgets3.2/libwxgtk-media3.2-1_3.2.2%2bdfsg-4_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/w/wxwidgets3.2/libwxgtk3.2-1_3.2.2%2bdfsg-4_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/n/netplan.io/netplan-generator_0.107-5ubuntu0.2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/n/netplan.io/netplan.io_0.107-5ubuntu0.2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/g/gpgme1.0/python3-gpg_1.18.0-3ubuntu2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/n/netplan.io/python3-netplan_0.107-5ubuntu0.2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/w/wxpython4.0/python3-wxgtk-media4.0_4.2.1%2bdfsg-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/w/wxpython4.0/python3-wxgtk4.0_4.2.1%2bdfsg-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/z/zope.interface/python3-zope.interface_5.5.2-1build1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/p/python3.11/python3.11_3.11.6-3_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/p/python3.11/python3.11-minimal_3.11.6-3_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/p/python3.11/python3.11-venv_3.11.6-3_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/r/ruby3.1/ruby3.1_3.1.2-7ubuntu3.1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/t/tcl8.6/tcl8.6_8.6.13%2bdfsg-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/t/tk8.6/tk8.6_8.6.13-2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/x/x11-apps/x11-apps_7.7%2b9_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/x/x11-session-utils/x11-session-utils_7.7%2b5_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/x/x11-xkb-utils/x11-xkb-utils_7.7%2b7_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/x/xauth/xauth_1.1.2-1_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/x/xbitmaps/xbitmaps_1.1.1-2.2_all.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/main/b/brltty/xbrlapi_6.5-7ubuntu2_amd64.deb
* http://tw.archive.ubuntu.com/ubuntu/pool/universe/x/xclip/xclip_0.13-2_amd64.deb

Not that it is insightful or anything.

**Comment by brlin-tw** [comment]
> All the HTTP requests that can readily reproduce the problem using the old version

I can verify that all these URLs can be successfully downloaded using the 41 version.

**Comment by pyamsoft** [comment]
A slight change was made to how TCP connections were exchanged in 41. Maybe this has also fixed your problem?

Either way, its good to hear that 41 seems to have resolved the issue. I hope in the next few days Google will approve the build so it can release on the Play Store.

**Comment by pyamsoft** [comment]
Can this be closed since the issue seems to be fixed in version 41?

**Comment by brlin-tw** [comment]
> Can this be closed since the issue seems to be fixed in version 41?

Yes, certainly.
