### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Dgfdgtbchjhh** [pyamsoft/tetherfi#282]
Hello I just wanted to ask does the tetherfi need Internet/wifi to work or not?

**Comment by pyamsoft** [comment]
Hello!

Yes, the tether shares your existing device Internet connection with other devices.

Your phone will run TetherFi, your other devices connect to your phone, and then any time your laptop wants to talk to the internet, the phone will "talk for it" basically, so the phone needs an Internet connection of some kind.

Hope that helps!
