### ISSUE TITLE
Can support setting up vpn in this app ?

### ISSUE THREAD

**Issue by HuixingWong** [pyamsoft/tetherfi#283]
Thank you for developing this amazing app. I would like to ask if it is possible to support vpn proxy setting in this app ？

**Comment by pyamsoft** [comment]
Do you mean for TetherFi to be the VPN app on your phone?

If so, unfortunately the answer is no. Google Play policy does not support an app using the VPN code on the device without actually connecting you to some kind of virtual network, and I interpret policy to mean that a simple proxy does not apply here.

If you mean something other than what I've interpreted, please let me know!

**Comment by HuixingWong** [comment]
Thank you for your reply， yes,  but maybe can consider release a different version app on fdroid ?

**Comment by pyamsoft** [comment]
I may consider it one day, but at the moment I lack the time to maintain 2 different flavors. I also have admittedly very little interest in attempting to make TetherFi a VPN app, as one of my chief use cases for the app in my own life is to use it to connect additional devices on-the-fly into a tailscale network. Sorry.

I am not saying no forever, though I am saying no for today.

**Comment by HuixingWong** [comment]
Anyway, thank you for maintaining this useful project.
