### ISSUE TITLE
WhatsApp communication capability 

### ISSUE THREAD

**Issue by NatalyLasse** [pyamsoft/tetherfi#288]
Hi Pyamsoft ! Thanks for the good work you are doing !
However, I am not able to communicate via WhatsApp.
Does it normally work ? If yes, please advise what to do !

**Comment by pyamsoft** [comment]
Hi!

tldr, no whatsapp isn't working yet. You can see our FAQ for a list of commonly not working apps.

Basically, anything owned by Meta hates proxy connections like the ones we make, so they actively try to break our connection.

At the moment, WhatsApp and all other Meta apps are unsupported, sorry :(
