### ISSUE TITLE
Potential memory leak in version 41

### ISSUE THREAD

**Issue by brlin-tw** [pyamsoft/tetherfi#291]
I am just being greeted by the LeakCanary UI after launching the application from the quick settings tile:

![Screenshot_20240502-171832](https://github.com/pyamsoft/tetherfi/assets/13408130/05735ceb-e999-4f2e-81a6-b6e945751644)
[2024-05-02_17-15-55_953.hprof.gz](https://github.com/pyamsoft/tetherfi/files/15186321/2024-05-02_17-15-55_953.hprof.gz)

**Comment by pyamsoft** [comment]
Are you running a debug build? Leak canary is not enabled in production

The Android OS has a memory leak in the TileService, there is nothing we can do about it sadly.

**Comment by brlin-tw** [comment]
> Are you running a debug build? Leak canary is not enabled in production

Yes, for testing #280.

> The Android OS has a memory leak in the TileService, there is nothing we can do about it sadly.

Thanks for the info, in that case I'm closing this, then.
