### ISSUE TITLE
Proxy service seems to be unintentially leaked to the external mobile network(version 41)

### ISSUE THREAD

**Issue by brlin-tw** [pyamsoft/tetherfi#292]
I notice the following screenshot has contained client IP addresses that are not from the Wi-Fi network interface:

![Screenshot_20240502-173715](https://github.com/pyamsoft/tetherfi/assets/13408130/1086fcbb-21c7-42f4-ab41-624d988021c5)

This is quite concerning as malicious actors on the mobile ISP network may use the proxy service for malicious activities, or infiltrate the device via the service's vulnerabilities.

I do not enable the "Bind Proxy to All Interface" option in the app settings(which is not toggleable anyway in version 41).

**Comment by pyamsoft** [comment]
How odd.

Given that the hotspot runs on a subnet that is different from the RFC and USB tethering space those IP addresses should not be showing at all.

You can toggle the switch off to disable the network traffic for those addresses, and in the future I can make the proxy drop connections to anything that is not in the same shared 192.168.49 space

**Comment by brlin-tw** [comment]
> You can toggle the switch off to disable the network traffic for those addresses

It is already off when the issue is reproduced, though as of now this is the only time where I can notice this symptom.

**Comment by pyamsoft** [comment]
The next version 42 will reject connections from any devices that are outside of the owning subnet. Basically, anything that is not 192.168.49.XXX in your screenshot above would be rejected from the proxy.

**Comment by pyamsoft** [comment]
With the release of version 43, this bug should be fixed by rejecting any connection outside of 192.168.49.XXX

Thank you for your contribution to the project!

**Comment by brlin-tw** [comment]
Thanks for the work!
