### ISSUE TITLE
Support I18N

### ISSUE THREAD

**Issue by brlin-tw** [pyamsoft/tetherfi#293]
I would like to translate the app to Taiwanese Chinese, however, it seems that the current UI strings aren't prepared to be translated yet.

**Comment by pyamsoft** [comment]
Very cool, thanks for the offer!

Right now, yes I'm not ready yet. To give you a general checklist of what I still need to get done for this to be feasible.

Right now basically all of the strings in the app are hardcoded English, as you've seen. I would need to move back to the Android resources system.

This app is built upon a library I also publish, called PYDroid, which provides a lot of common code like the settings page and popup dialogs. That library will need to be fully moved to the resource system as well.

- Migrate PYDroid (english) to resources
- Migrate TetherFi (english) to resources

Once these are both done, then I would be open to accepting translations.
This will take a bit of time, so sorry in advance, but I appreciate your kind offer!

**Comment by pyamsoft** [comment]
With the release of version 43, we have migrated away from hardcoded English strings in many places. The app should be running almost entirely off the Android resources system again, which will open the door now for translations into other languages.

Thank you for your contribution to the project!

**Comment by brlin-tw** [comment]
Thanks for the work!
