### ISSUE TITLE
Hotspot showing up just not sharing wifi

### ISSUE THREAD

**Issue by christiaansp** [pyamsoft/tetherfi#297]
I have this running on a Galaxy tab A8, dont ask why. But when I turn the hotspot on, it shows as an internet connection but just doesn't share the wifi connection to my phone, it just says "(hotspot name) has no internet access)" and yes my tablet does have an active internet connection. Does anybody know how to fix this issue? (I tried 2.4ghz, 5ghz, and have practically every setting on in the tweaks)

**Comment by pyamsoft** [comment]
Have you followed the proxy setup instructions? By default, the proxy will not have normal internet access until you setup a manual HTTP proxy

**Comment by christiaansp** [comment]
How do I do that exactly?

**Comment by pyamsoft** [comment]
There are instructions in the app, and a link to a dedicated Wiki page with instructions

https://github.com/pyamsoft/tetherfi/wiki/Setup-A-Proxy

**Comment by christiaansp** [comment]
Thanks, got it working now :)
