### ISSUE TITLE
IOT devices wifi connected

### ISSUE THREAD

**Issue by cemkadir86** [pyamsoft/tetherfi#301]
Hello, I want to use your application as a server to connect my iot devices. I create a wifi network from your application. IOT devices connect to the application's IP address as a client. Then I want to send and receive data through the application. How can I do it? Which part do I need to intervene? I am new to Android. 

Thank you in advance for your help.

**Comment by pyamsoft** [comment]
Hi

There is an instruction page in the app and more on the Wiki here on Github.

You need to setup a proxy for your devices which should allow them simple HTTP based communication over TCP with the current TetherFi version

**Comment by cemkadir86** [comment]
Thank you very much for the quick response. I connect 2 different devices and there is no problem. But I am trying to exchange data between the IOT device and my Android phone with tethered connection. I could not find any documentation about it.

**Comment by pyamsoft** [comment]
Your IOT device needs to be able to support connection over an HTTP proxy. Since I don't know what your device is, I cannot provide more specifics, but if it can not proxy, then it sadly will not work.

**Comment by cemkadir86** [comment]
Actually my device is an esp32. There is no problem in establishing a wifi connection. Actually I need a plugin that shows the data that comes after you open the network and establish a connection. I am trying to do that.
