### ISSUE TITLE
Wifi id and pass about

### ISSUE THREAD

**Issue by cemkadir86** [pyamsoft/tetherfi#303]
Hi, Static entry of wifi name and password is blocked by Android. How did you overcome this issue without root?

**Comment by pyamsoft** [comment]
Hi, if you are seeing the "system defined" text, your Android device is on a version before the ability to change the name and password existed.

You'll need to update your Android OS version if possible.

**Comment by cemkadir86** [comment]
Under which file can I find the wifi hotspot start and wifi hotspot ssid entry in the code?

**Comment by pyamsoft** [comment]
The connectChannel function inside of  https://github.com/pyamsoft/tetherfi/blob/main/server/src/main/java/com/pyamsoft/tetherfi/server/broadcast/wifidirect/WifiDirectNetwork.kt handles setting up the network name and password

**Comment by cemkadir86** [comment]
Thanks for help. It worked very well.

**Comment by pyamsoft** [comment]
No problem.

If you're a Dev, the WiFi direct back end on some phones won't accept a password less than 8 characters long. Just a heads up!

**Comment by cemkadir86** [comment]
Yes, I am a developer but I am new to Android. Are you sure that it is wifi direct, because when I use tetherfi, I can see the wifi network on my iPhone. But when I try wifidirect, my iPhone cannot see the wifi network.

**Comment by pyamsoft** [comment]
WiFi direct in TetherFi is setup using what's called a Group, which is considered the "legacy" way. The "normal" WiFi direct on the phone uses the new way, which doesn't broadcast a visible network.

There's a lot of code in this app that sets up the WiFi direct network. A lot of sweat and blood went into figuring out how it all works :)

**Comment by cemkadir86** [comment]
Yes it looks very difficult. :D I hope you continue your work. Congratulations.
