### ISSUE TITLE
Simple is beautiful

### ISSUE THREAD

**Issue by gogo16888** [pyamsoft/tetherfi#305]
Tetherfi only needs to set up the WiFi properly, and other VPN apps can implement such  proxies. IP address and DHCP settings cannot be set yet in Tetherfi.

**Comment by pyamsoft** [comment]
Hello, sorry, I am not sure I understand. Do you have a question, or is this an observation?

**Comment by gogo16888** [comment]
This is just one suggestion.
















At 2024-06-15 09:14:05, "pyamsoft" ***@***.***> wrote:

Hello, sorry, I am not sure I understand. Do you have a question, or is this an observation?

**Comment by pyamsoft** [comment]
Ah I see, then I think there is a misunderstanding.

TetherFi uses WiFi direct to setup the WiFi properly, which we have very little control over.

Once started, the Android OS system runs a DHCP server and assigns a host IP address.

We have zero control over these steps, there is no option for us to not do one or the other.

Yes, any app can make the proxy server part, but the WiFi direct IP address, and DHCP are non configurable.

**Comment by gogo16888** [comment]
Yes. I found that root privileges are required to access the gateway's IP and DHCP. However, the setting of the proxy port is relatively redundant, and the successful connection seems to be unrelated to the hotspot, it is connecting to the proxy port. And most VPNs are designed very well for this. If the proxy port is removed, the connection indication directly utilizes the connection information of the hotspot, which is actually more specific and dedicated; It is positioned as a new Tether app.




At 2024-06-18 20:44:17, "pyamsoft" ***@***.***> wrote:

Ah I see, then I think there is a misunderstanding.

TetherFi uses WiFi direct to setup the WiFi properly, which we have very little control over.

Once started, the Android OS system runs a DHCP server and assigns a host IP address.

We have zero control over these steps, there is no option for us to not do one or the other.

Yes, any app can make the proxy server part, but the WiFi direct IP address, and DHCP are non configurable.

**Comment by pyamsoft** [comment]
Yes that is true, but a regular WiFi direct hotspot is local only and thus has no connection to the Internet.

The proxy is needed to allow the device to receive forwarded connections from client devices.

You don't have to use the proxy built into TetherFi, and can use any app you want that provides a host side forwarding setup.
