### ISSUE TITLE
Shortcut

### ISSUE THREAD

**Issue by vizctas** [pyamsoft/tetherfi#306]
There is any chance to add a shortcut to directly start the connection?

I'm trying to automatically start the tethering with macroid/tasker.

**Comment by pyamsoft** [comment]
Could be possible, right now there is only a tile. I can look at adding a shortcut in the future

**Comment by pyamsoft** [comment]
I hope to have something for this in the next release, 44

**Comment by pyamsoft** [comment]
44 is in pre-release testing on the Google Play Store.

**Comment by pyamsoft** [comment]
A shortcut to "Toggle Hotspot" has been added in 44, which has just been released on the Google Play Store
