### ISSUE TITLE
The Check for Updates option doesn't appeared to be working(at least visually when no updates are found)

### ISSUE THREAD

**Issue by brlin-tw** [pyamsoft/tetherfi#309]
## Current behavior

After tapping the option nothing happens.

[Clip that shows the problem](https://github.com/pyamsoft/tetherfi/assets/13408130/0a0e7dd3-dbfa-4473-b369-eba74ccc1eec "Clip that shows the problem")

## Expected behavior

TetherFi should at the very least have a toast notification saying that no updates are available.

## Developer logs

```log
[D] (SourceFile:66) App Update info received: com.google.android.play.core.appupdate.AppUpdateInfo@a3917d8 
[D] (SourceFile:112) Update is not available 
[D] (SourceFile:92) Update data found as: com.pyamsoft.pydroid.bootstrap.version.update.AppUpdateLauncher$Companion$empty$1@8a32731 
[D] (SourceFile:199) Done checking for updates 
```

## More information

This section documents the additional information that may or may not help investigate this issue:

### Application version

43

### Device brand and model

Google Pixel 8 Pro

### Device processor architecture

ARM64

### OS version

14 (AP2A.240605.024)

### Locale

zh-rTW

**Comment by pyamsoft** [comment]
This is working as intended. I suppose I could add an extra snack bar to display no updates found, but the google in app update API is already very brittle and difficult to interface with.

**Comment by pyamsoft** [comment]
A change has been made to pydroid (the internal pyamsoft library that powers this feature)

When a version check is made explicitly by the user clicking the button, a snackbar will show visual feedback for "checking update" and "no update found" or "update available"

Please see [here](https://github.com/pyamsoft/pydroid/commit/0ee051da85252ced89f14bf5c64262acef42b2d1)
for more details. This feature will release in the next version 44!

**Comment by pyamsoft** [comment]
44 is in pre-release testing on the Google Play Store.

**Comment by pyamsoft** [comment]
The visual UI for checking for updates has been added to version 44, which has just been released on the Play store.

**Comment by brlin-tw** [comment]
I've installed the 44 version, and it works without issues; thanks!
