### ISSUE TITLE
TetherFi on OpenAPK

### ISSUE THREAD

**Issue by mobilenetworkltd** [pyamsoft/tetherfi#316]
Hey,

I'm running a repo for Android open source apps at https://www.openapk.net and I would like to have TetherFi listed in the repo. Please review the listing at https://www.openapk.net/tetherfi/com.pyamsoft.tetherfi/

It is hooked to your GitHub repo so all the updates are automatically pushed to OpenAPK. Let me know if its ok !

If you are interested you can link to it and use our download banners ( https://www.openapk.net/images/openapk-badge.png )

**Comment by pyamsoft** [comment]
Hello, thank you for creating a listing for TetherFi on your service.

I haven't heard of OpenAPK before, I will consider adding the badge in the future to the README, but I will need to look over the platform first. Thank you for your contribution to the project, and thank you for your interest!

**Comment by mobilenetworkltd** [comment]
Hello,

thank you for the time having a conversation and considering this. Be aware that we link directly to the Github releases, we don't build APK files or store them. Looking forward for your comments.
