### ISSUE TITLE
wifi keep getting disconnected in miui

### ISSUE THREAD

**Issue by anvrag** [pyamsoft/tetherfi#318]
hey, so i have a old xioami phone which is running on android 7 and miui 11 and yeah i am using it as wifi extender, the app is working good but my wifi keeps getting disconnected after the screen is off for more than 30 mins or +, is it possible to give a option in app to keep the screen awake or any other settings which i can perform, thanks.

**Comment by pyamsoft** [comment]
Make sure the Keep Alive option is on and that the app is whitelisted in whatever Xaomis custom battery saving thing is.

Otherwise I will look at some option to force the screen to stay on, but in the mean time you can adjust the screen timeout in your device system settings.

**Comment by anvrag** [comment]
every setting is turned on and i did have added the app into exceptions list of battery optimization. and yeah i am using the screen timeout thingy but i have to adjust it every time when i am not using the phone as a extender. thanks ill wait for an update.

**Comment by pyamsoft** [comment]
I have added a Tweak to Keep Screen On, which will be released with the next version 45

As long as the main TetherFi page stays open, the screen will stay on. Also, for devices which support it, TetherFi will hold a "wake lock" which will keep the CPU on and the screen on, even if you close the main TetherFi page.

I have no estimated date yet for when I will release the update, so I appreciate your patience. I am sorry this has taken so long, but rest assured I have not forgotten about you :)

Thank you for your contribution to the project! I will close this issue once 45 releases!

**Comment by pyamsoft** [comment]
Version 45 is in beta in the store and should be released sometime this or next week. Thank you!

**Comment by pyamsoft** [comment]
Version 47 has been released to the store which brings support for this Keep Screen On tweak. Thank you for your contribution!
