### ISSUE TITLE
connect to windowd 10

### ISSUE THREAD

**Issue by shockergit** [pyamsoft/tetherfi#326]
How do i share internet from my android to windows 10. I havent found any instructions in github

**Comment by pyamsoft** [comment]
Hi

There is an instruction page im the app and some deeper dive instructions here on github, but to summarize

Start the hotspot by clicking the button in the app

On your windows machine, go to the Network and Internet settings and setup a Manual Mode HTTP Proxy.

Take a peek at the wiki here on github which should include some simple screenshots

**Comment by shockergit** [comment]
> Hi
> 
> There is an instruction page im the app and some deeper dive instructions here on github, but to summarize
> 
> Start the hotspot by clicking the button in the app
> 
> On your windows machine, go to the Network and Internet settings and setup a Manual Mode HTTP Proxy.
> 
> Take a peek at the wiki here on github which should include some simple screenshots

Thanks it works
