### ISSUE TITLE
DNS address could not be found

### ISSUE THREAD

**Issue by Schweiger-Jacob** [pyamsoft/tetherfi#327]
I'm trying to use the app to charge Internet with my Linux mint laptop. It connects to the network but when trying to access a site it will say the DNS cannot be found.

**Comment by pyamsoft** [comment]
Make sure your resolve.conf points the upstream DNS to the proxy IP at 192.168.49.1.

If its going somewhere else, then the DNS request is not going through TetherFi and it won't work.

**Comment by Schweiger-Jacob** [comment]
I tried replacing nameserver 127.0.0.53 with 192.168.49.1 but the same problem persisted.

**Comment by Schweiger-Jacob** [comment]
I'm not sure it's just a DNS issue since when I try pinging 1.1.1.1 or 8.8.8.8 I get destination net unreachable

**Comment by pyamsoft** [comment]
For ping in a terminal, it won't work over TetherFi currently because the proxy doesn't support ICMP.

You could use curl instead. For your browser, also make sure you are not using DNS over HTTPS

**Comment by Schweiger-Jacob** [comment]
turning off secure dns in the browser appears to have fixed it. Thanks for the help.
