### ISSUE TITLE
Option to always tether Mobile Data and prevent tethering WiFi data

### ISSUE THREAD

**Issue by MohammedALShimmary** [pyamsoft/tetherfi#331]
I was wondering if you can add a feature to only tether mobile data. Because whenever i come a cross known Wi-Fi access point , the TetherFi just switch automatically tethering the WiFi internet not the 4G LTE, and I can't turn off the wifi because TetherFi needs it and I don't want to forgot every WiFi access point i come across.

There is a function in the developer options where you can force 4G LTE all the time even if the WiFi is connected, but that option drain so much battery and I tested it and still TetherFi doesn't use the 4G LTE internet.

**Comment by pyamsoft** [comment]
Hello,

I have thought about this previously in #154 and earlier, though no work has started on it yet.
