### ISSUE TITLE
Connected device limit?

### ISSUE THREAD

**Issue by randev4** [pyamsoft/tetherfi#332]
May I know if theres a limit in the number of connected devices? Im a teacher and I wish to create a hotspot that can connect 40 Android devices so that I can easily share files with students

**Comment by pyamsoft** [comment]
Hi

There is no enforced limit, but I have not personally tested above 8 devices.

Given that your phone is running the hotspot I assume it would struggle dealing with more than 10 devices.

I recommend you investigate a more robust solution to serve 40 students. Perhaps a samba file share or a shared classroom link to a Google Drive could solve your problem better?
