### ISSUE TITLE
VPN connection sharing 

### ISSUE THREAD

**Issue by kcryptonian** [pyamsoft/tetherfi#333]
Hi. Well done for your efforts. But please can you add a feature to the app where it's possible to share or tether one's VPN connection with another device?
An example is this: https://play.google.com/store/apps/details?id=com.iorgana.vpnshare

I very much desire this feature, having it would make TetherFi a complete tethering application.

**Comment by pyamsoft** [comment]
Hi, depending on your VPN it may already be possible.

If your VPN has a setting to allow local connections, then running your VPN on your TetherFi device would already share connections to it.

I use this myself to connect multiple devices to a TailScale network.
