### ISSUE TITLE
Incompatible app: Kizzy

### ISSUE THREAD

**Issue by Clyde6790pGIT** [pyamsoft/tetherfi#340]
A Discord RPC app called "Kizzy" https://github.com/dead8309/Kizzy does not function and will crash on a TetherFi hotspot as it uses websockets, can this be added to the incompatible apps list?

**Comment by pyamsoft** [comment]
Thank you

I will add this to the documentation wiki list once I am at my machine

Since Kizzy is open, I wonder if they would be interested in adding support for proxy HTTP connections (if that is the protocol they use)
