### ISSUE TITLE
Failed to resolve: io.ktor:ktor-network:3.0.1-PYAMSOFT

### ISSUE THREAD

**Issue by douglasNordenstedt** [pyamsoft/tetherfi#348]
### Im trying to run the source code in android studio but it seems to have failed to download some of the dependencies? 
This is the log from the build: 

Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find io.ktor:ktor-network:3.0.1-PYAMSOFT.
Searched in the following locations:
  - file:/home/user01/.m2/repository/io/ktor/ktor-network/3.0.1-PYAMSOFT/ktor-network-3.0.1-PYAMSOFT.pom
  - https://plugins.gradle.org/m2/io/ktor/ktor-network/3.0.1-PYAMSOFT/ktor-network-3.0.1-PYAMSOFT.pom
  - https://dl.google.com/dl/android/maven2/io/ktor/ktor-network/3.0.1-PYAMSOFT/ktor-network-3.0.1-PYAMSOFT.pom
  - https://repo.maven.apache.org/maven2/io/ktor/ktor-network/3.0.1-PYAMSOFT/ktor-network-3.0.1-PYAMSOFT.pom

**Comment by pyamsoft** [comment]
Hi

The project uses a custom fork of ktor that you'll also need to build.

You can find the ktor fork in my repositories.

**Comment by brlin-tw** [comment]
# Some notes for rebuilding ktor for use in TetherFi

[You may not need to unless you need the preferred network future](https://github.com/pyamsoft/tetherfi/issues/351#issuecomment-2458472250)

Avoid building ktor directly in Android Studio(unless you know how to correctly do it), the project targets multiple platforms(Android, iOS(tvos, watchos, etc...), Kotlin, Linux, Windows...)  and is very large, and most of them aren't really used in TetherFi, dependency resolution for all the build targets takes forever(>2hr) at my end and should be avoided.

The process in general would be:

1. Install Gradle(the one provided by Ubuntu 24.04 works), OpenJDK, Git, and [other build dependencies of ktor](https://github.com/ktorio/ktor/blob/main/CONTRIBUTING.md#building-the-project).
2. Clone a copy of the [pyamsoft/ktor Git repository](https://github.com/pyamsoft/ktor).
3. Launch a text terminal.
4. Change the working directory to the local ktor source tree.
5. Run the following commands to build and publish the packages to the local Maven repository:
    + `./gradlew publishKotlinMultiplatformPublicationToMavenLocal`
    + `./gradlew publishJvmPublicationToMavenLocal`
6. Verifies files are published in the ~/.m2/repository/ directory.
7. Build TetherFi as usual.
