### ISSUE TITLE
Developer log should redact access point password info

### ISSUE THREAD

**Issue by brlin-tw** [pyamsoft/tetherfi#350]
Currently, the user-specified access point authentication password is exposed in the developer log:

```
[D] Network info update accepted: GRP=Connected(ssid=DIRECT-TF-brlin, password=0123456789) CON=Connected(hostName=192.168.49.1)
```

As such information may be used in a [Credential stuffing](https://en.wikipedia.org/wiki/Credential_stuffing) attack we probably should redact it by default.

### TetherFi

49 from Google Play

### Android

14 (AP2A.240905.003)

### Phone

Google Pixel 8 Pro

**Comment by pyamsoft** [comment]
Addressed in this commit: 9c4b42250a4a7e0b9b260b666ae658dd0eec44d0

Most likely for release 50

Thank you!
