### ISSUE TITLE
"Use Cellular Data" option not enabling Cellular connection when WiFi is on

### ISSUE THREAD

**Issue by 7eventech77** [pyamsoft/tetherfi#358]
I am on the latest version of the app and noticed that #154 & #272 were closed and fixed as of the latest version. Wanted to report that whenever I start the TetherFi hotspot with the following parameters the cellular data icon does not show up nor is cellular or WiFi internet connection used. In apps like NetShare with a similar option the cellular icon appears whenever the hotspot is started when WiFi is on and connected to a network.
Paremeters
- WiFi enabled & connected to network
- All needed permissions are granted & enabled
- Preferred network set to "Cellular"
- Cellular data turned on
- Tried with "Mobile data always active" on and off in developer settings, no difference

Is there any way with what tools you have to have the Cellular Data "turn on" whenever WiFi is connected to a network so that TetherFi can use the data instead?

Not sure if I am using this feature incorrectly, there is a bug, or what I am talking about is not supported in this new feature in TetherFi. If you need logs or pictures then feel free to ask me how and where to get them.

Thank you in advance!

**Comment by pyamsoft** [comment]
Hi, TetherFi will provide the cellular data connection to the clients it connects to. You can test this if your device is supported by checking the IP address on the connected device.

You should see a different IP address when forced onto cellular instead of WiFi.

**Comment by 7eventech77** [comment]
Hello, I just tried forcing over both WiFi or cellular (Not sure if I am doing it correctly) and the IP address of the device I'm hotspotting to (Microsoft Surface Go 2) from (Samsung A23 5G) stays the same with "192.168.49.233" on either. Is this normal or is something else going on?

Thank you!

**Comment by pyamsoft** [comment]
Hi,

I mean that your public IP will be different, so under WiFi your connected device public IP will be the same as your phone. When forced over cellular data, it will generally be different.

**Comment by 7eventech77** [comment]
Hello,

I finally was able to verify that the cellular was being used instead of WiFi when still connected to a WiFi network by using my data usage counter on my phone and see if the usage goes up or not. Just extremely weird how the "LTE" icon is not showing up whenever the cellular is being used and wasn't aware of this behavior. Thank you for your help!

**Comment by pyamsoft** [comment]
Yes, since this feature is using a "background network" to save some additional battery, the phone will not actually display anything different like a data symbol.

Its an odd side effect, but sadly there is nothing I can do about it.

Thanks for the good question :)
