### ISSUE TITLE
Whatsapp Telegram VPN or connect to Remote Desktop 

### ISSUE THREAD

**Issue by zannas88** [pyamsoft/tetherfi#360]
Hi, thanks for the app. Is in the near featured possible to use one of these services while connected via thetherfi?

Many thanks

**Comment by pyamsoft** [comment]
WhatsApp and Telegram is probably never without another external tool setup.

On an Android device, the operating system only enforces that the default web browser use the proxy. So we can't actually force apps like WhatsApp to use our connection, its very dumb. But it is what it is.


VPNs may work depending on the VPN used. As long as it allows access to the local area network, a VPN should work. You can try adjusting the toggle in the app.

Remote desktop is a maybe based on whether the remote desktop uses UDP protocol and can support a SOCKS proxy.

In general, compatibility with other apps is not up to TetherFi, but up to the app itself sadly.

Hope this helps.

**Comment by zannas88** [comment]
Thanks so much for the reply. Hope to see soon the UDP protocol in order to use the remote desktop.

About VPN, I use Tailscale, actually doesn't work, but I'm not so skilled to understand why .

Again, thank so much for your work, I will wait the improvements, but take your time with no stress ;)

**Comment by pyamsoft** [comment]
TailScale will work on a computer if you launch the tailscaled daemon with http Proxy variables, thats at least how I use it on Linux

**Comment by brlin-tw** [comment]
Note that the Telegram Android app. supports connecting the service via a SOCKS proxy service, I've tried this with the recent TetherFi version that supports SOCKS proxy(via the 8229 port) and it works.
