### ISSUE TITLE
No Internet 

### ISSUE THREAD

**Issue by Stanredmond** [pyamsoft/tetherfi#362]
Been using this app for a few days and everything worked great. I use the hotspot on my PC to log in as administrator since I need a password to log in on PC. Windows 10. This morning go to log in and says I have no Internet. Nothing has been changed on PC or phone. Cannot even get in my PC now

**Comment by pyamsoft** [comment]
Have you tried restarting the TetherFi hotspot?

I'd also try restarting your phone and PC.

I'm not exactly clear on what your login problem is, sorry. Do you mind clarifying more? Screenshots of both TetherFi and your PC would also be helpful, as long ad you are comfortable sharing them.
